- tools/goctl/api/gogen/genroutes.go
- tools/goctl/api/ktgen/funcs.go
- tools/goctl/api/ktgen/gen.go
修复问题：
- 1.Kotlin HttpUrlConnection在连接失败或者超时之后抛出的Exception没有catch
- 2.生成的API命名问题：函数名前加入了Method名，防止有些接口URI相同但是方法不同，导致生成的Kotlin函数重复
- 3.修复了`/users/:id`这样的路径参数导致生成的Kotlin函数名带有冒号的问题
- 4.添加了连接超时3秒
- 5.goctl添加了HTTP PATCH方法支持
关于接口函数命名，应该以方法名+路由URI作为这个接口的唯一表示，这样才能保证生成的函数名不会重复。
比如这几个Restful API
- get /users
- get /users/:id
- post /users
- put /users
- delete /users/:id
生成的客户端接口函数名分别是
- getUsers()
- getUsersWithId()
- postUsers()
- putUsers()
- deleteUsersWithId()
> goctl生成Kotlin代码优化

- tools/goctl/model/sql/gen/delete.go
- tools/goctl/model/sql/gen/fineonebyfield.go
- tools/goctl/model/sql/gen/keys.go
- tools/goctl/model/sql/parser/parser.go
> findOneByField() 之前包含了unique、normal、spatial三类索引处理
* 修改后：只处理unique索引
> 修复model自动生成中findOneByField()方法

- tools/goctl/api/gogen/genhandlers.go
1. 所删逻辑和types包导入没有关系
2. 如果不删除，当request结构体不存在时，response结构体存在时会导致types这个无用的包import
> 修复goctl api代码

- example/tracing/edge/config.json
- example/tracing/edge/main.go
1.补上一些缺失的配置
2.原配置中的api端口号与代码中不一致（写死）
> fix example tracing edge config

- example/rpc/client/stream/client.go
1.原来接收Recv的协程是个死循环。
2.main在Send三次后直接退出了，看不到Recv的输出。
> fix rpc client example

- core/errorx/atomicerror.go
- core/errorx/atomicerror_test.go
This commit optimizes AtomicError using atomic.Value. Benchmarks:
```
name                 old time/op  new time/op  delta
AtomicError/Load-6   305ns ±11%    12ns ± 6%  -96.18%  (p=0.000 n=10+10)
AtomicError/Set-6    314ns ±16%    14ns ± 2%  -95.61%  (p=0.000 n=10+9)
```
> optimize AtomicError

- core/trace/tracespec/vars.go
should not use basic type string as key in context.WithValue,
context.WithValue method Doc:
```
// The provided key must be comparable and should not be of type
// string or any other built-in type to avoid collisions between
// packages using context. Users of WithValue should define their own
// types for keys. To avoid allocating when assigning to an
// interface{}, context keys often have concrete type
// struct{}. Alternatively, exported context key variables' static
// type should be a pointer or interface.
```
> fix: golint: context.WithValue should should not use basic type as key

- core/bloom/bloom.go
参考 https://help.aliyun.com/document_detail/92942.html?spm=5176.13910061.sslink.1.36426f0dV6cOrU
阿里云的文档，如果按照以前的写法会出现如下错误
```bash
redis cluster, all the keys that the script uses should be passed using the KEYS arrayrn
```
> 修复阿里云集群 redis KEYS 的错误。

- tools/goctl/rpc/gen/genmain.go
add defer s.Stop() to mainTemplate, in order to stop rpc server when main function exit
> stop rpc server when main function exit

- core/fx/fn.go
- core/fx/fn_test.go
When n is less than 1 , fx/Stream Head func will forever block , this pull request will fix it.
> fix: fx/fn.Head func will forever block when n is less than 1

- tools/goctl/api/format/format.go
- tools/goctl/api/gogen/gen.go
- tools/goctl/goctl.go
Add stdin flag to use stdin receive api doc and use stdout output formatted result.
This pull request can make the vscode-goctl extension not need to flash the api file to the disk when formatting.
@kingxt  @anqiansong
> goctl add stdin flag

- tools/goctl/Makefile
- `command -v upx &> /dev/null && upx goctl`这样的写法无法达到预期的目的（若已安装upx则执行upx goctl）。若实际未安装upx，执行这条指令报错。
- 方式一：卸载upx，再执行make。
- 方式二: 重置`PATH`环境变量，将upx所在目录（如`/usr/local/bin`）排除在PATH环境变量之外，再执行make。
- 使用Makefile的`if`函数判断upx是否已经安装，若已经安装，则执行upx goctl。
> Improve Makefile robustness

- core/logx/tracelogger_test.go
tracelogger_test.go 中 TestTraceLog 测试失败，没有初始化 initialized 变量为 1，导致测试不通过
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestTraceLog$ github.com/tal-tech/go-zero/core/logx
2020/12/10 15:18:14 {"@timestamp":"2020-12-10T15:18:14.825+08","level":"info","content":"Stay hungry, stay foolish.","trace":"mock-trace-id","span":"mock-span-id"}
--- FAIL: TestTraceLog (0.00s)
/Users/wayne/learning-projects/go-learn/github-projects/tal-tech-go-zero/core/logx/tracelogger_test.go:26: 
Error Trace:	tracelogger_test.go:26
Error:      	Should be true
Test:       	TestTraceLog
/Users/wayne/learning-projects/go-learn/github-projects/tal-tech-go-zero/core/logx/tracelogger_test.go:27: 
Error Trace:	tracelogger_test.go:27
Error:      	Should be true
Test:       	TestTraceLog
FAIL
FAIL …
> fix tracelogger_test TestTraceLog

- core/conf/config.go
- core/conf/config_test.go
增加在配置文件加载时，可以从环境变量中加载相关信息，便于保护私密信息
原有代码：
```go
return loader(content, v)
```
修改后:
```go
return loader([]byte(os.ExpandEnv(string(content))), v)
```
相关的test也修改了,具体参考commit文件
> add config load support env var

- rest/handler/authhandler.go
- rest/handler/authhandler_test.go
- rest/handler/cryptionhandler.go
- rest/handler/cryptionhandler_test.go
- rest/handler/loghandler.go
- rest/handler/loghandler_test.go
- rest/internal/security/withcoderesponsewriter.go
- rest/internal/security/withcoderesponsewriter_test.go
- To support http.Flush
> source code : https://github.com/jichangyun/bookstore
```
func (l *CheckLogic) Check(w http.ResponseWriter, req types.CheckReq) (*types.CheckResp, error) {
flusher, ok := w.(http.Flusher)
if !ok {
l.Logger.Errorf("Writer is not a Flusher. w: %v.", w)
return nil, errors.New("ResponseWriter unsupport Flusher!")
}
// 先返回头部信息
w.Header().Set("Content-Type", "application/json")
w.Header().Set("Transfer-Encoding", "chunked")
w.WriteHeader(http.StatusOK)
flusher.Flush()
fmt.Fprintf(w, "Start return value.\n")
flusher.Flush()
for i := 0; i < 5; i++ {
time.Sleep(time.Duration(i) * time.Second)
fmt.Fprintf(w, "Return value %d after sleep %d second.\n", i, i)
flusher.Flush()
}
return &types.CheckResp{}, nil
}
```
- Use chorme to visit …
> The ResponseWriters defined in rest.handler add Flush interface.

- tools/goctl/rpc/generator/gensvc.go
rpc中的config不是公开的
api中的config是公开的
这里修改了rpc中的生成模板，进行统一
> modify the goctl gensvc template

- core/collection/rollingwindow.go
- core/collection/rollingwindow_test.go
滑动窗口的lasTime记录的是更新offset时的时间戳，这样无法准确计算offset，应该是记录当前窗口的起始时间，旧代码跑TestRollingWindowAdd2会输出：{0, 1, 20},正确结果应该是{1, 5, 15}
> fix rolling window bug

- tools/goctl/api/format/format.go
- tools/goctl/api/parser/parser.go
> code optimized

- core/proc/shutdown+polyfill.go
When I bind two socket on one port or other start problem ; pannic is nil pointer
expect: return Error info
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x854174]
goroutine 1 [running]:
github.com/tal-tech/go-zero/rest/internal.start(0x0, 0x0, 0xd05, 0x1444058, 0xc000096120, 0x987060, 0xa10640, 0xc00008a2d0)
problem:
waitForCalled := proc.AddWrapUpListener(func() {
server.Shutdown(context.Background())
})
defer waitForCalled()
func AddWrapUpListener/AddShutdownListener(fn fnc()) (func ())
return nil
so that 
fix return nil --> return fn
> fix server.start return nil points

- core/stat/internal/cgroup_linux.go
/proc/[pid]/cgroup中如果出现逗号","只保存逗号分割后的信息
> fix cgroup bug

- rest/config.go
之前http server（rest）支持的最大content-length限制为8MB，
如果，在一些场景下，比如上传一个小视频这类，会导致服务端拒绝
所以，这里适当的给最大值放大一些，提供更多的选择
> modify the maximum content-length to 30MB

- zrpc/config.go
- zrpc/internal/clientinterceptors/timeoutinterceptor.go
zrpc client支持不设置超时时间，默认超时时间通过配置文件中默认参数传入
> zrpc client support block

- core/logx/config.go
- core/logx/logs.go
为 logx 增加 time format 和 time zone 设置选项，默认为中国时区，效果如下： 2021-03-19T16:00:39.556+08
> add timezone and timeformat

- core/contextx/deadline.go
`contextx.ShrinkDeadline` 和标准库的 `context.WithTimeout` 是等价的。
标准库的 `context.WithDeadline` 已经做了 deadline 的计算（和 ShrinkDeadline 计算的原理相同），不会让派生的子 context 的 deadline 比父 context 晚。
> Simplify contextx.ShrinkDeadline

- core/breaker/googlebreaker.go
- core/collection/timingwheel.go
- core/discov/internal/listener.go
- core/hash/consistenthash.go
- core/logx/tracelogger_test.go
- core/mapping/utils.go
- core/stores/cache/cachenode.go
- core/stores/kv/store.go
- core/stores/mongoc/cachedcollection.go
- core/stores/mongoc/cachedmodel.go
- core/stores/redis/redis.go
- core/stringx/strings.go
- rest/engine_test.go
- rest/httpx/router.go
- tools/goctl/api/docgen/doc.go
- tools/goctl/api/parser/g4/ast/api.go
- tools/goctl/api/parser/g4/ast/apiparser.go
- tools/goctl/model/sql/gen/keys_test.go
- tools/goctl/model/sql/test/model/studentmodel.go
- tools/goctl/plugin/plugin.go
- tools/goctl/rpc/execx/execx.go
```sh
find . -name "*.go" | xargs gofumpt -l -s -w -extra
```
https://github.com/mvdan/gofumpt
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
> chore(format): change by gofumpt tool

- tools/goctl/model/mongo/template/template.go
- tools/goctl/model/sql/gen/keys.go
- tools/goctl/model/sql/gen/keys_test.go
* replace cache key with colon
if you have plan to use the latest cache templates of model, which changed the cache key splitter from `#` to `:`,
you must execute command `goctl template` to update the model templates, for more information of update template, please see `goctl template -h`
> replace cache key with colon

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
使用多维切片的时候报错：panic: reflect.Set: value of type []interface {} is not assignable to type []string
对应测试用例为
`func TestUnmarshalJsonReaderMultiArray(t *testing.T) {
payload := `{"a": "133", "b": [["add", "cccd"], ["eeee"]]}`
var res struct {
A string     `json:"a"`
B [][]string `json:"b"`
}
reader := strings.NewReader(payload)
err := UnmarshalJsonReader(reader, &res)
assert.Nil(t, err)
assert.Equal(t, 2, len(res.B))
}`
使用基础类型指针切片的时候对应的值未被反序列化
对应测试用例为：
func TestUnmarshalJsonReaderPtrArray(t *testing.T) {
payload := `{"a": "133", "b": ["add", "cccd", "eeee"]}`
var res struct {
A string    `json:"a"`
B []*string `json:"b"`
}
reader := strings.NewReader(payload)
err := UnmarshalJsonReader(reader, &res)
assert.Nil(t, err)
assert.Equal(t, 3, len(res.B))
}
结果：
> 修复不支持多维度切片以及不支持基本类型指针切片

- tools/goctl/goctl.go
- tools/goctl/rpc/README.md
- tools/goctl/rpc/cli/cli.go
- tools/goctl/rpc/generator/defaultgenerator.go
- tools/goctl/rpc/generator/gen.go
- tools/goctl/rpc/generator/gen_test.go
- tools/goctl/rpc/generator/generator.go
- tools/goctl/rpc/generator/genpb.go
Maintain compatibility with version github.com/golang/protobuf/protoc-gen-go@v1.4.0
`--go_opt` usage please see https://developers.google.com/protocol-buffers/docs/reference/go-generated#package
> Add go_opt flag

- core/proc/shutdown.go
- rest/internal/starter.go
Fixed [#796](https://github.com/tal-tech/go-zero/issues/796)
> Fixed http listener error.

- tools/goctl/rpc/generator/genserver.go
生成的server方法里少了context，因为notStream这个变量只定义在了genFunctions中
GenServer中使用的serverTemplate没有notStream这个变量，导致生成的server的import里永远少了context
> fix context missing

- tools/goctl/model/mongo/template/template.go
* Use  package `mongo`  without `--cache`
* Remove argument `cache.CacheConf`  while generating  without `--cache`
> optimize mongo generation without cache (fix #881)

- tools/goctl/model/sql/model/postgresqlmodel.go
- tools/goctl/rpc/cli/cli.go
- tools/goctl/util/env/env.go
- tools/goctl/vars/settings.go
* Optimize `go`, `protoc`, `protoc-gen-go` environment detection
* Check if the current OS supports `exec.Command` or `os.StartProcess` to start processes
> optimize grpc generation env check

- core/stores/redis/redis.go
- core/stores/redis/redis_test.go
当我在集群模式下，不能使用mget操作，用redis.Pipelined实现多个get操作来模拟mget操作，需要StringCmd
// StringCmd is an alias of redis.StringCmd.
StringCmd = red.StringCmd
> redis.go，type StringCmd = red.StringCmd

- core/trace/constants.go
- core/trace/propagator_test.go
- core/trace/span.go
- core/trace/span_test.go
- core/trace/spancontext.go
- rest/handler/tracinghandler.go
- rest/handler/tracinghandler_test.go
目的:
方便前端同事发现接口错误时, 可提供traceId给后端技术快速定位错误日志
> Add traceId to the response headers

- core/opentelemetry/agent.go
- core/opentelemetry/attributes.go
- core/opentelemetry/clientstream.go
- core/opentelemetry/config.go
- core/opentelemetry/message.go
- core/opentelemetry/serverstream.go
- core/opentelemetry/tracer.go
- core/opentelemetry/utils.go
- core/service/serviceconf.go
- go.mod
- go.sum
- zrpc/internal/client.go
- zrpc/internal/clientinterceptors/opentracinginterceptor.go
- zrpc/internal/clientinterceptors/opentracinginterceptor_test.go
- zrpc/internal/rpcserver.go
- zrpc/internal/serverinterceptors/opentracinginterceptor.go
- zrpc/internal/serverinterceptors/opentracinginterceptor_test.go
实现了opentelemetry的链路跟踪方案，对接jaeger
目前尚未添加stream的中间件。收集方案仅添加了jaeger
> add the opentelemetry tracing

- core/opentelemetry/agent.go
- core/opentelemetry/config.go
- core/service/serviceconf.go
- rest/engine.go
- rest/handler/otelhandler.go
- rest/handler/otelhandler_test.go
- zrpc/internal/clientinterceptors/opentracinginterceptor.go
- zrpc/internal/serverinterceptors/opentracinginterceptor.go
> rest otel support

- zrpc/err.go
- zrpc/internal/codes/accept.go
- zrpc/internal/codes/accept_test.go
- zrpc/internal/serverinterceptors/timeoutinterceptor.go
- zrpc/internal/serverinterceptors/timeoutinterceptor_test.go
目的:
将context返回的错误,转换成grpc可以识别的错误
该PR合并后,以下代码将永远不会被执行,应该移除它
https://github.com/tal-tech/go-zero/blob/d0f9e5702289b32b5d289ad2418d8b91b0807c6e/zrpc/internal/codes/accept.go#L24-L25
> Fix context error in grpc

- tools/goctl/api/new/newservice.go
- tools/goctl/util/ctx/gomod.go
- tools/goctl/util/ctx/gopath.go
- tools/goctl/util/path.go
- tools/goctl/util/path_test.go
* fix #968 
* Add `ReadLink`  method to get the destination of the named symbolic link recursively. see [util/path.go](https://github.com/tal-tech/go-zero/blob/master/tools/goctl/util/path.go)
> Fix filepath

- tools/goctl/api/gogen/genhandlers.go
- tools/goctl/goctl.go
- tools/goctl/internal/errorx/errorx._test.go
- tools/goctl/internal/errorx/errorx.go
- tools/goctl/internal/version/version.go
- tools/goctl/internal/version/version_test.go
- tools/goctl/util/templatex.go
```
missing -o
```
```
goctl: generation error: missing -o
goctl version: 1.1.11-beta-1 darwin/amd64
```
> Feature goctl error wrap

- tools/goctl/model/sql/builderx/builder.go
- tools/goctl/model/sql/builderx/builder_test.go
- tools/goctl/model/sql/gen/update.go
- zrpc/internal/clientinterceptors/opentracinginterceptor.go
**修改前**
生成的更新语句
`update t set a=$1,b=$2 where id=$1`
执行参数顺序
`data.a, data.b, data.id`
**修改后**
`update t set a=$2,b=$3 where id=$1`
执行参数顺序
`data.id, data.a, data.b`
> 修复使用 postgres 数据库时，位置参数重复，导致参数与值不对应的问题。

- rest/internal/log.go
goroutine panic后，RecoverHandler函数的log日志无traceid
> feat: change logger to traceLogger for getting traceId when recovering

- core/trace/opentelemetry/agent.go
we can use otel.ErrorHandlerFunc instead of custom struct when we update OpenTelemetry to 1.0.0
> use otel.ErrorHandlerFunc

- tools/goctl/rpc/generator/gencall.go
the order of range map is random, causing the order of proto-message aliases to be different every time
> when run goctl-rpc, the order of proto message aliases should be fixed

- .github/workflows/go.yml
Reverts zeromicro/go-zero#1084
Checks succeeded, but not with go-version not a valid field.
> Revert "chore: run unit test with go 1.14"

- tools/goctl/rpc/generator/genmain.go
Modify the rpc template file, when the mode is dev and test, provide publicly accessible gRPC service, which is convenient for using grpc client tool to call.
> feat: reflection grpc service

- zrpc/client.go
- zrpc/config.go
- zrpc/internal/client.go
- zrpc/internal/client_test.go
1. use WithBlock() by default
2. NonBlock can be set in config or WithNonBlock() option
> feat: rpc dial can be set with NonBlock mode

- rest/engine.go
- rest/engine_test.go
- rest/server.go
- rest/server_test.go
- rest/types.go
Usage:
```go
srv.AddRoute(rest.Route{
Method:  http.MethodGet,
Path:    "/hello",
Handler: handleHomeHello,
}, rest.WithTimeout(time.Second))
srv.AddRoutes([]rest.Route{
{
Method:  http.MethodGet,
Path:    "/hello",
Handler: handleApiHello,
},
{
Method:  http.MethodGet,
Path:    "/hi",
Handler: handleApiHi,
},
}, rest.WithPrefix("/api"), rest.WithTimeout(time.Second*5))
```
> feat: support customizing timeout for specific route

- rest/internal/cors/handlers.go
- rest/internal/cors/handlers_test.go
- rest/server.go
- rest/server_test.go
Adding this limitation because writing body and calling WriteHeader will cause confusing in middleware.
> chore: only allow cors middleware to change headers

- zrpc/internal/balancer/p2c/p2c.go
p2c.subConn int64字段未对其，导致在Pick中choose(p.conns[0], nil)报错，p2c.go:153
> fix: go issue 16206

- rest/handler/loghandler.go
排除 【当客户端主动中断一个请求，服务会记录一条503错误日志】 的情况
> 排除客户端中断导致的503错误

- tools/goctl/api/new/newservice.go
- tools/goctl/goctl.go
add a option for api new
goctl api new  utils.api -style go_zero
> go-zero tools ,fix a func,api new can not choose style

- core/stores/redis/redislock.go
- core/stores/redis/redislock_test.go
fix redis try-lock bug
#issue_id: 1338
> fix redis try-lock bug

- tools/goctl/model/sql/gen/field.go
- tools/goctl/model/sql/parser/parser.go
现有`user.sql`
~~~sql
CREATE TABLE `user` (
`id` int(8) NOT NULL AUTO_INCREMENT,
`type` int(8) NOT NULL DEFAULT '0' COMMENT '类型',
PRIMARY KEY (`id`),
KEY `uid` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
~~~
在执行`goctl model mysql ddl -src="./user.sql" -dir="." -c` 时提示如下
~~~bash
[EscapeGolangKeyword]: go keyword is forbidden "type", converted into "tp"
~~~
生成的代码中User struct如下
~~~go
User struct {
Id int64 `db:"id"`
Tp int64 `db:"tp"` // 类型
}
~~~
此代码需要将 `db:"tp"` 改为 `db:"type"` 方可使用，此即当前PR解决的问题。
> Updated MySQL生成表结构体遇到关键字db部分保持原字段名定义

- readme-cn.md
这里的链接应该是迁移文档之后忘了改了？: )
是要改成 https://github.com/zeromicro/zero-doc/blob/main/docs/zero/goctl-api.md 吗？
> fix readme-cn

- core/logx/config.go
- core/logx/durationlogger.go
- core/logx/durationlogger_test.go
- core/logx/logs.go
- core/logx/logs_test.go
- core/logx/tracelogger.go
- core/logx/tracelogger_test.go
- rest/handler/loghandler.go
> feat: implement console plain output for debug logs

- tools/goctl/api/parser/g4/ast/apiparser.go
- tools/goctl/api/parser/g4/gen/api/baseparser.go
- tools/goctl/api/parser/g4/gen/api/baseparser_test.go
`importValueRegex` now can match more path formats
Resolves: #1568
> feat: supports `importValue` for more path formats

- core/collection/fifo_test.go
cover the case of non-zero value for q.Header when q.Elements expands
> test: add testcase for FIFO Queue in collection module

- tools/goctl/api/parser/g4/gen/api/apiparser_parser.go
- tools/goctl/api/parser/g4/gen/api/file_splitor_test.go
Each time test `TestFileSplitor` is executed, an extra newline will be generated at the end of the file `apiparser_parser.go`.
> fix: fix(gctl): apiparser_parser auto format

- tools/goctl/api/format/format.go
- tools/goctl/api/format/format_test.go
- tools/goctl/api/gogen/gen.go
- tools/goctl/api/parser/g4/ast/apiparser.go
- tools/goctl/api/parser/parser.go
- tools/goctl/goctl.go
maybe I just want to format api files
> feat:Support for referencing types in different API files using format

- tools/goctl/model/sql/template/delete.go
`FindOne` method is a generated one.
> fix(goctl): model method FindOneCtx should be FindOne

- core/stores/builder/builder.go
- core/stores/builder/builder_test.go
The new function RawFieldNames  has considered the following that the tag could have option.
```go
//`db:"id"`
//`db:"id,type=char,length=16"`
//`db:",type=char,length=16"`
```
> fix: the new  RawFieldNames considers the tag with options.

- tools/goctl/model/sql/gen/insert.go
- tools/goctl/model/sql/template/insert.go
在生成model代码指定-cache=true时，如果表中只有主键没有其他唯一索引时候，insert是不删除缓存的，但是findone会查缓存，这样会有问题在findone不存在的数据时候会缓存* ，那先findone在insert就会有问题
When the generated model code specifies - cache = true, if there is only a primary key in the table and there is no other unique index, the insert will not delete the cache, but findone will check the cache, which will cause problems. If there is no data in findone, it will cache *, then findone will have problems in the insert first
> fix -cache=true insert no clean cache

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
support for empty slce, Same behavior as json.Unmarshal
json.Unmarshal
```
%!p(logic.A={[]})
false
[]
```
code
```go
type A struct {
AA []struct {
C string
}
}
var c = A{}
reader := io.LimitReader(strings.NewReader(`{"AA":[]}`), 10000)
err = mapping.UnmarshalJsonReader(reader, &c)
if err != nil {
t.Fatal(err)
}
fmt.Printf("%#p\n", c)
fmt.Println(c.AA == nil)
fmt.Println(c.AA)
```
before:
```
%!p(logic.A={[]})
true
[]
```
after:
```
%!p(logic.A={[]})
false
[]
```
> fix: empty slice are set to nil

- tools/goctl/api/format/format.go
- tools/goctl/api/format/format_test.go
resolves #1721
There's also a relative PR https://github.com/zeromicro/goctl-vscode/pull/12
> fix(goctl): api format with reader input

- rest/engine.go
- rest/engine_test.go
- rest/server.go
- rest/types.go
- tools/goctl/api/gogen/genroutes.go
It can be used like this
```go
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
server.AddRoutes(
[]rest.Route{
{
Method:  http.MethodPost,
Path:    "/upload",
Handler: UploadHandler(serverCtx),
},
},
rest.WithMaxBytes(52428800),
)
}
```
custom timeout and maxbytes in api file can be used like this
The unit of timeout is `time.Second`
```go
@server(
timeout: 2
maxBytes: 1234
group: user
)
service user {
@handler getUser // etst
get /users/id (request) returns (response)
}
```
general code 
```go
// Code generated by goctl. DO NOT EDIT.
package handler
import (
"net/http"
"time"
user "joj-backend/api/internal/handler/user"
"joj-backend/api/internal/svc"
"github.com/zeromicro/go-zero/rest"
)
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) …
```
> Added support for setting the parameter size accepted by the interface and custom timeout and maxbytes in API file

- tools/goctl/model/sql/gen/gen.go
- tools/goctl/model/sql/gen/imports.go
- tools/goctl/model/sql/gen/tablename.go
- tools/goctl/model/sql/gen/template.go
- tools/goctl/model/sql/template/delete.go
- tools/goctl/model/sql/template/errors.go
- tools/goctl/model/sql/template/field.go
- tools/goctl/model/sql/template/find.go
- tools/goctl/model/sql/template/import.go
- tools/goctl/model/sql/template/insert.go
- tools/goctl/model/sql/template/model.go
- tools/goctl/model/sql/template/new.go
- tools/goctl/model/sql/template/tablename.go
- tools/goctl/model/sql/template/tag.go
- tools/goctl/model/sql/template/types.go
- tools/goctl/model/sql/template/update.go
- tools/goctl/model/sql/template/vars.go
Separate the model generation into `xxxmodel_gen.go` and `xxxmodel.go`.
Don't edit `xxxmodel_gen.go`, it will be overwritten on regeneration. And extend the sql operations on `xxxmodel.go`.
`xxxmodel.go` looks like:
> feat: let model customizable

- tools/goctl/model/sql/gen/field.go
- tools/goctl/model/sql/gen/insert.go
- tools/goctl/model/sql/gen/update.go
situation: column name with line.
CREATE TABLE test (
id int NOT NULL AUTO_INCREMENT,
zh-cn text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '中文简体',
PRIMARY KEY (id) USING BTREE,
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
> fix bug: crash when generate model with goctl.

- rest/httpx/responses.go
- rest/httpx/responses_test.go
Only the first WriteHeader call takes effect.
https://github.com/golang/go/blob/master/src/net/http/server.go#L1135-L1148
> fix: rest: WriteJson get 200 when Marshal failed.

- tools/goctl/goctl.go
- tools/goctl/model/sql/command/command.go
- tools/goctl/model/sql/command/command_test.go
See #1794
```
+------------------+
| Tables_in_gozero |
+------------------+
| user             |
| order            |
| pay              |
| after_sale       |
| product          |
+------------------+
```
```shell
$ goctl model mysql datasource --table user --dir .
```
```
$ tree
.
├── usermodel.go
└── usermodel_gen.go
```
```shell
$ goctl model mysql datasource --table="*er" --dir .
```
```
$ tree
.
├── ordermodel.go
├── ordermodel_gen.go
├── usermodel.go
└── usermodel_gen.go
```
The same way to generate single table to before
way 1:
```shell
$ goctl model mysql datasource --table user --table order --dir .
```
way 2:
```shell
$ goctl model mysql datasource --table="user,order"
```
```shell
$ goctl model mysql datasource --table user --table="*er"
```
Result:
```
$ tree
.
├── …
```
> feat: Support model code generation for multi tables

- tools/goctl/model/sql/gen/gen.go
- tools/goctl/util/ctx/gomod.go
The package name of model comes from the name of the output directory. If this value does not satisfy the golang naming convention, it will cause code generation to fail, so we must handle this value effectively。
If the target path is not in any go module mode and is not under GOPATH, the module value obtained by executing go list -json -m is `command-line-arguments`, which is not a valid go module value and needs to be handled effectively to prevent
```shell
$ GO111MODULE=on go list -json -m
{
"Path": "command-line-arguments",
"Main": true,
"GoVersion": "1.18"
}
```
> fix: Code generation

- core/mr/mapreduce.go
In mr.foreach function, because mapper does not need to write to collector, collector can be initialized as an unbuffered channel.
> core/mr:a little optimization for collector initialization in ForEach function

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
fix: 修复fillSliceFromString()方法中mapValue 强转string后的panic 错误
> fix: panic on convert to string on fillSliceFromString()

- tools/goctl/api/cmd.go
fix goctl api, use default(master) branch, clone remote template fail
> fix goctl api clone template fail

- rest/httpx/responses.go
- rest/httpx/responses_test.go
- rest/internal/errcode/grpc.go
- rest/internal/errcode/grpc_test.go
- zrpc/internal/codes/accept.go
- zrpc/internal/serverinterceptors/timeoutinterceptor.go
For RESTful services, it might send requests to gRPC services to complete the user requests. And by default, it's better to detect the gRPC errors and return the correct HTTP status code to clients.
> feat: convert grpc errors to http status codes

- readme.md
The documentation link https://go-zero.dev/en/ is a dead link, update to a new valid link. Please take a look.
> Fix dead doc link

- rest/internal/starter.go
> fix: `\u003cnil\u003e` log output when http server shutdown.

- core/discov/internal/registry.go
there should be locked, when delete key-value in `c.values`.
``` go
case clientv3.EventTypeDelete:
if vals, ok := c.values[key]; ok {
delete(vals, string(ev.Kv.Key))
}
for _, l := range listeners {
l.OnDelete(KV{
Key: string(ev.Kv.Key),
Val: string(ev.Kv.Value),
})
}
```
> fix concurrent map read and map write

- rest/server.go
- rest/server_test.go
feat https://github.com/zeromicro/go-zero/issues/2096
> feat:Add `Routes` method for server

- tools/goctl/api/gogen/genhandlers.go
- tools/goctl/api/gogen/handler.tpl
fix: goctl genhandler duplicate rest/httpx & goctl genhandler template support custom import httpx package
Reason:
1、在 handler 层，我对 httpx 包进行了再次封装
2、在某些情况下，我需要控制 httpx 包的导入
3、goctl 1.3.9 会出现两个 rest/httpx 包
Example:
```
package {{.PkgName}}
import (
"net/http"
"appservice/pkg/resultx"
{{.ImportPackages}}
{{if .HasRequest}}
{{.ImportHttpxPackage}}
{{end}}
)
func {{.HandlerName}}(svcCtx *svc.ServiceContext) http.HandlerFunc {
return func(w http.ResponseWriter, r *http.Request) {
{{if .HasRequest}}var req types.{{.RequestType}}
if err := httpx.Parse(r, &req); err != nil {
resultx.HttpParamErrorResult(r, w, err)
return
}
{{end}}l := {{.LogicName}}.New{{.LogicType}}(r.Context(), svcCtx)
{{if .HasResp}}resp, {{end}}err := l.{{.Call}}({{if .HasRequest}}&req{{end}})
{{if …
```
> fix: goctl genhandler duplicate rest/httpx & template import custom

- core/logx/config.go
- core/logx/logs.go
- core/logx/readme-cn.md
- core/logx/readme.md
- core/logx/rotatelogger.go
- core/logx/rotatelogger_test.go
- core/logx/writer.go
implementation of #1652
Totally compatible with the old logx.LogConf. No effect if users do not change their options.
> feat: logx support logs rotation based on size limitation. (#1652)

- tools/goctl/api/parser/g4/ast/apiparser.go
fix: goctl genroute check duplicate route 
在a有prefix，b无prefix下会出现异常报错，实际上加上prefix并无重复
Reason:
a.api
@server (
group: foo
prefix: foo
)
service api {
@handler templatesget
get /templates (req)  returns (res)
}
b.api
@server (
group: bar
)
service api {
@handler templatesget
get /templates (req)  returns (res)
}
> fix:duplicate route check

- core/logx/contextlogger_test.go
constant testlog "Stay hungry, stay foolish." contains foo(foolish), changed to foo1
> fix: logx test foo

- core/collection/cache.go
Use an instead of 'a' if the following word starts with a vowel sound, e.g. 'an in-memory cache'. 
> fix: fix comment typo

- core/stat/internal/cpu_linux.go
Fixes #2019 for AWS Lambda scenarios when `stat` does not poll cpu
> Initialize CPU stat only if used

- core/syncx/resourcemanager.go
- core/syncx/resourcemanager_test.go
after resource manager close reuse this manager to get resource, it would be a dead lock
```go
// playground
manager := NewResourceManager()
defer manager.Close()
_, err := manager.GetResource("key", func() (io.Closer, error) {
return nil, errors.New("fail")
})
assert.NotNil(t, err)
if assert.NoError(t, manager.Close()) {
_, err = manager.GetResource("key", func() (io.Closer, error) {
return nil, errors.New("fail")
})
assert.NotNil(t, err)
// !!! here should be a panic
assert.Panics(t, func() {
_, err = manager.GetResource("key", func() (io.Closer, error) {
return &dummyResource{age: 123}, nil
})
})
}
```
> fix resource manager dead lock

- core/mapping/marshaler_test.go
- core/mapping/utils.go
使用range定义范围的时候,left>right 定义不应该通过，虽然validate的时候有报错，感觉可用加一下。个人愚见^_^
> improve: number range compare left and righ value

- tools/goctl/api/docgen/doc.go
- tools/goctl/api/gogen/gentypes.go
- tools/goctl/api/gogen/testdata/api_common.api
- tools/goctl/api/gogen/testdata/api_has_nested_type.api
- tools/goctl/api/gogen/util.go
Provides the ability to generate nested types 
like
```go
type CommonResponse {
Code    int    `json:"code"` // 100 | 200
Message string `json:"message"`
}
type UserCreateDto {
Id string `json:"id"`
}
type UserCreateResponse {
CommonResponse
Result *UserCreateDto `json:"result"` // result
}
```
is generate to 
```go
type UserCreateResponse struct  {
Code    int    `json:"code"` // 100 | 200
Message string `json:"message"`
Result struct {
Id string `json:"id"`
} `json:"result"` // result
}
```
> generates nested types in doc

- rest/router/patrouter_test.go
It seems that the test case is incorrect.
> correct test case

- core/logx/config.go
- core/logx/logger.go
- core/logx/logs.go
- core/logx/logs_test.go
- core/logx/richlogger.go
- core/logx/richlogger_test.go
- core/logx/vars.go
- core/logx/writer.go
> feat: add log debug level

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
> fix: add more tests

- tools/goctl/model/mongo/generate/generate.go
Before this, no matter what style is used, lowercase file names without underscores will be generated.
> fix(mongo): fix file name generation errors

- tools/goctl/api/spec/example_test.go
- tools/goctl/api/spec/fn.go
- tools/goctl/api/tsgen/util.go
- tools/goctl/api/tsgen/util_test.go
When generating the api code of typescript, if the tag contains the options modifier, the union type is generated instead of the declared type. Here is an example.
Api:
```api
type SomeType {
Foo string `json:"foo,options=foo,bar,options,123"`
Bar int `json:"bar,options=1,3,4,123"`
}
```
Typescript:
```typescript
export interface SomeType {
foo: 'foo' | 'bar' | 'options' | '123'
bar: 1 | 3 | 4 | 123
}
```
This can provide a good intelligent complement for the front-end IDE.
I have completed  the test file.
> feat(goctl): better generate the api code of typescript

- core/limit/tokenlimit.go
- core/limit/tokenlimit_test.go
supported token limiter with context using option func mode, if not set, using context.backgroud as default
```go
// example
s, err := miniredis.Run()
assert.Nil(t, err)
l := NewTokenLimiter(rate, burst, redis.New(s.Addr()), "tokenlimit")
defer s.Close()
// use cuxtom ctx
ctx, cancel := context.WithCancel(context.Background())
ok := l.Allow(WithTokenCtx(ctx))
assert.True(t, ok)
```
> token limit support context

- tools/goctl/model/mongo/readme.md
- tools/goctl/model/mongo/template/model.tpl
Fix the wrong key about FindOne in mongo of goctl.
> Fix the wrong key about FindOne in mongo of goctl.

- .github/workflows/go.yml
- .github/workflows/issue-translator.yml
- .github/workflows/issues.yml
-  [x] waiting for merge https://github.com/usthe/issues-translate-action/pull/72
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
> chore(action): upgrade actions/stale & actions/setup-go & codecov/codecov-action

- core/stores/redis/hook.go
- core/stores/redis/hook_test.go
in AfterProcessPipeline function，"logDuration(ctx, cmds[0], duration)" will print pipeline's first command
> fix: redis's pipeline logs are not printed completely

- rest/handler/tracinghandler.go
- rest/handler/tracinghandler_test.go
> fix(rest): fix issues#2628

- core/logx/rotatelogger.go
When application restart, the currentSize reset to 0.
If it uses fileSizeRotation, the size will larger than max size, but not rotate.
> fix: log currentSize should not be 0 when file exists and size is not 0

- tools/goctl/go.mod
- tools/goctl/util/stringx/string.go
- tools/goctl/util/stringx/string_test.go
strings.Title is Deprecated, because the rule Title uses for word boundaries does not handle Unicode
> replace strings.Title to cases.Title

- gateway/server.go
- rest/handler/timeouthandler.go
- rest/httpx/responses.go
- rest/httpx/responses_test.go
- tools/goctl/api/gogen/handler.tpl
Context can be injected into the api global error response result event to achieve full link logging.
For example:
Method httpx.SetErrorHandler combination https://github.com/pkg/errors ,errors.Warp，errors.WithMessage is very popular. Development engineers do not need to manually output logs for error processing.
Because of the unified err interception and link log context output.
> feature : responses whit context

- core/stores/builder/builder.go
- core/stores/builder/builder_test.go
```
type mockedUserWithDashTagAndOptions struct {
ID       string `db:"id" json:"id,omitempty"`
UserName string `db:"user_name,type=varchar,length=255" json:"userName,omitempty"`
Mobile   string `db:"-,type=varchar,length=255" json:"mobile,omitempty"`
}
```
Given a struct above, a call to RawFieldNames(...) will produce a slice like {"`id`", "`user_name`", "`-`"}, which is not expected. Currently, the ignore feature is only works when struct tag is pure dash, without any options.
> RawFieldNames should ignore the field whose name is start with a dash

- core/collection/ring.go
Like RollingWindow, Ring can also uses RWMutex instead of Mutex, Which enables mutiple Take op in the same time.
> Use read-write lock instead of mutex

- rest/server.go
- rest/server_test.go
Is similar to gin-gonic , allow developer to do a unit test with all defined router without starting a HTTP Server.
For example:
server := MustNewServer(...)
server.addRoute(...) // router a
server.addRoute(...) // router b
server.addRoute(...) // router c
req, _ := http.NewRequest(...) 
w := httptest.NewRecorder(...)
server.ServeHTTP(w,req)
//TODO : test after response
> add ServeHTTP to Server/Engin for doing Httptest

- core/trace/agent.go
- core/trace/agent_test.go
#2379 Fixed the issue that the GRPC exporter did not establish an RPC link 原文使用的 otlptracegrpc.NewUnstarted创建的是一个未建立rpc连接的导出器，无法正常使用；改为otlptracegrpc.New才妥
> :bug: debug grpc export (#2379)

- tools/goctl/api/cmd.go
- tools/goctl/compare/cmd/cmd.go
- tools/goctl/rpc/cmd.go
ExactValidArgs is Deprecated
use MatchAll(ExactArgs(n), OnlyValidArgs) instead
> fix: replace goctl ExactValidArgs to MatchAll

- rest/config.go
- rest/engine.go
- rest/handler/tracinghandler.go
- rest/handler/tracinghandler_test.go
BREAKING CHANGE: remove `handler.DontTraceSpan` function, please use `rest.RestConf.TraceIgnorePaths` instead.
> refactor(rest): use static config for trace ignore paths.

- core/collection/timingwheel.go
- core/collection/timingwheel_test.go
It would be convenient if we could expose `newTimingWheelWithClock()` to the endpoint user.
Closes #2786 . The issue contains more details.
> expose `collection.newTimingWheelWithClock()`

- tools/goctl/api/gogen/genroutes.go
custom maxBytes in api file can be used like this
```go
type Request {
Name string `path:"name,options=you|me"`
}
type Response {
Message string `json:"message"`
}
@server(
maxBytes: 1024
)
service A-api {
@handler GreetHandler
get /greet/from/:name(Request) returns (Response)
}
```
general code
```go
// Code generated by goctl. DO NOT EDIT.
package handler
import (
"net/http"
"test/internal/svc"
"github.com/zeromicro/go-zero/rest"
)
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
server.AddRoutes(
[]rest.Route{
{
Method:  http.MethodGet,
Path:    "/greet/from/:name",
Handler: GreetHandler(serverCtx),
},
},
rest.WithMaxBytes(1024),
)
}
```
For example, in the application of single architecture, there is a function to upload excel files and import data. At this …
> support custom maxBytes in API file

- core/stringx/node.go
- core/stringx/replacer.go
- core/stringx/replacer_test.go
In the `Replace` method,  the replacer replace the shortest first match word, not the longest word said [in the doc](https://go-zero.dev/docs/blog/tool/keywords).
> fix #2835， replace shoud replace the longest match

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
only unmashal public variables
> only unmashal public variables

- tools/goctl/api/dartgen/genapi.go
- tools/goctl/api/dartgen/util.go
- tools/goctl/api/dartgen/vars.go
Fix Dart API generation bugs; Add ability to generate API for path parameters
Suppose I have a following API definition, filename is `greet.api`:
```
service greet-api {
@handler GreetHandler
get /from/:name(GreetRequest) returns (GreetResponse)
}
```
Actual dart file path is `../data/greet-api.dart`
Generated import path is `import '../data/greet.dart'`. This is **WRONG** because it took the `greet.api` file name by mistake.
This bug was solved by replacing the import path to the actual file path. Now it looks like this:
`import '../data/greet-api.dart'`
Generated dart function name is: 
```dart
Future apiFrom:name( 
{Function(GreetResponse)? ok,
Function(String)? fail,
Function? eventually}) async {
await apiGet('/from/:name',
ok: (data) {
if (ok != null) …
```
> Fix Dart API generation bugs; Add ability to generate API for path parameters

- tools/goctl/api/dartgen/util.go
This PR fixes the bug in previous PR: https://github.com/zeromicro/go-zero/pull/2887
Bug: `pathTagKey` was used by mistake, whose value is always `path`.
Now it is fixed.
> Fix bug in dart api gen: path parameter is not replaced

- rest/handler/timeouthandler.go
- rest/handler/timeouthandler_test.go
fix
interface conversion: *handler.timeoutWriter is not http.Hijacker: missing method Hijack
> interface conversion: *handler.timeoutWriter is not http.Hijacker: missing method Hijack

- core/stores/postgres/postgresql.go
"github.com/jackc/pgx/v5",  Pgx will not be loaded sql/drivers，Proper init should use "github.com/jackc/pgx/v5/stdlib"
> init postgresql err

- core/discov/config.go
- core/discov/config_test.go
- zrpc/internal/clientinterceptors/tracinginterceptor.go
- zrpc/internal/rpcpubserver.go
When registering the zrpc server, if you choose the ETCD method to register, the ID in the Publisher used during registration does not support modification in NewRpcPubServer, resulting in the final registration of zrpc to the server, which can only be key+leaseID. Therefore, if you want to add the ServerID field to the configuration file of ETCD, you can **customize the key+id registered in ETCD key.**
> Added zrpc server custom serverID for custom registration Key when the service is registered on ETCD.

- core/stores/sqlx/orm.go
- core/stores/sqlx/orm_test.go
When using orm, a problem was found. When you use QueryRowsPartial to get a small number of query fields, the scanner scans the struct in the order it was passed in, causing an err
The following structure:
err：
> fix  QueryRowsPartial  getTaggedFieldValueMap func

- rest/engine.go
- rest/server.go
单体服务部署时需要支持热更新,一些开源方案如overseer等需要使用http Serve,gozero的internal.StartHttp是支持StartOption的,但是Server Start不支持设置,发起pr支持start时自定义StartOption
> defines the method to customize http server

- tools/goctl/api/dartgen/gendata.go
- tools/goctl/api/dartgen/util.go
- tools/goctl/api/dartgen/vars.go
e.g. When data type is double and data value is 1, dart catch error as shown in the following figure
so I use the num type to be compatible with double and int
> Fix bug: replace int and float with num type in dart

- core/bloom/bloom.go
- core/limit/periodlimit.go
- core/limit/tokenlimit.go
- core/stores/redis/redis.go
- core/stores/redis/redis_test.go
- core/stores/redis/redislock.go
https://redis.uptrace.dev/guide/lua-scripting.html#redis-script
The go-redis docs says:
```
Internally, go-redis uses EVALSHA to execute the script and fallbacks to EVAL if the script does not exist.
```
> feat(redis): add ScriptRun API and migrate EvalCtx to ScriptRun for limit, lock and bloom

- tools/goctl/api/ktgen/api.tpl
- tools/goctl/api/ktgen/gen.go
> Fix the problem of package name for generated kt code.

- gateway/server.go
Fix the problem that the default grpc-gateway connects to the rpc server timeout
bug issue: #3140
reason: https://github.com/zeromicro/go-zero/commit/0d5a68869dbc06db9fed6ed429a6b301e4b9f176#diff-4652d1bf175a0be8f5e61ef7177c9666f23e077d8626b73ac9d13358fa8b525b
> fix default grpc-gateway connect timeout

- core/prometheus/agent.go
- internal/devserver/server.go
`DevServer` aim to replace old prometheus agent, but the global switcher of prometheus pkg is not enable when using `DevServer`.
> fix(metrics): enable prometheus global switch when user enable devsever metrics

- tools/goctl/api/format/format.go
- tools/goctl/api/format/format_test.go
before this, there will be meaningless tabs between multiple request definitions.
> no \t to space line

- tools/goctl/api/dartgen/gendata.go
- tools/goctl/api/dartgen/util.go
- tools/goctl/api/dartgen/vars.go
Suppose we have a `hello.api` looks like this:
```go
// hello.api
type Greet {
Items []*GreetItem `json:"greet"`
}
type GreetItems {
FirstName string `json:"firstName"`
LastName string `json:"lastName"`
}
```
**Current Behavior**
Currently, the generated `.dart` code could not compile, because variable `i` whose type is `GreetItem?` is not null safe.
If the one of the list item variable `i` is null, the the code will crash.
```dart
class Greet {
final List<GreetItem?> items;
Greet({
required this.items,
});
factory Greet.fromJson(Map<String, dynamic> m) {
return Greet(
items: ((m['greet'] ?? []) as List<dynamic>)
.map((i) => GreetItem?.fromJson(i))
.toList(),
);
}
Map<String, dynamic> toJson() {
return {
'greet': items.map((i) => i.toJson()),         #### Could not compile
};
}
}
``` …
> [dart-gen] Fix nullable list item issue

- core/discov/internal/registry.go
- core/discov/internal/vars.go
- go.mod
- go.sum
- zrpc/internal/client.go
More than 3 pings between the keepalive period causes the server responding "too many pings" error. Even it doesn't affect the service, but it's better to avoid it.
Autosync make the synchronization reliable, even when the ETCD server recovered from a outage.
> fix: remove etcd pings to avoid too-many-pings error

- go.mod
- go.sum
- internal/devserver/server.go
Under Go 1.19, there might be STW problems when goroutines > 1k.
> chore: remove fgprof, use pprof directly

- rest/engine.go
- rest/handler/prometheushandler.go
- rest/handler/prometheushandler_test.go
Add 'method' label for prometheus middleware metrics to resolve issue #3076
> Add method label for prometheus middleware metrics

- core/fx/retry.go
- core/fx/retry_test.go
In order to prevent repeated execution of certain methods, the DoWithTry method has been extended to support timeout and interval control due to the assumption that the situation is blocking, resulting in unrestricted waiting and too frequent retries
Adding context parameters can determine whether the program terminates before executing critical operations
The newly added part has been tested and does not affect the original functionality. It also meets expectations for timeout and interval control.
To avoid accidental situations, these three testing methods were executed dozens of times
> note: The possible impact of this change is that if a variable other than fn is called in the first parameter fn of the original DowithRetry method and is modified, a race error may occur
> update: expand the retry method to support timeout and interval control

- core/stores/sqlc/cachedsql.go
add expiration time for redis #2431
> feat: sqlc add SetCacheWithExpire method

- tools/goctl/util/ctx/gomod.go
- tools/goctl/util/ctx/gomod_test.go
In windows10,I want to expenrience go-zero
In execute `goctl new api demo`,occur `occur error `invalid character 'A' looking for beginning of value`
The reason for this error is that my Windows computer is set to use UTF-8 character encoding, so when executing the cmd, there will be a prompt at the beginning saying 'Active code page: 65001', causing issues when validating the JSON format.
windows10下,我想体验go-zero
在执行goctl new api demo时,出现invalid character 'A' looking for beginning of value 的错误
这个错误的原因是我的Windows电脑设置为使用UTF-8字符编码,所以在执行cmd时,开头会有一个提示说'Active code page: 65001',导致验证JSON格式时出问题。
befor:
after
> fix In `goctl new api`, occur error `invalid character 'A' looking for beginning of value`

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
add a feature I proposed in #3386
> feat: add detail type mismatch info in number fields check (#3386)

- core/metric/histogram_test.go
- core/metric/summary.go
- core/metric/summary_test.go
- core/proc/shutdown.go
**feat**: This pr provides the code about Prometheus summary metrics
Before submitting this pr, I thought about it for a long time. In fact, Prometheus's native histogram can do what summary needs to do. However, the function of histogram only overlaps with that of suammary. In some scenarios, I don't think it can replace summary.
Here are a few reasons for adding summary metrics
+ **The histogram metric type in Prometheus also has its own issues**.
Too low precision for calculated percentiles when the exported histogram buckets have insufficient coverage for the measurement. For example, if `http_request_duration_seconds` histogram has the following buckets: `[0-0.1]`, `(0.1-1.0]`, `(1.0-10.0]` - and the majority of requests are executed in 0.5 seconds, then all these requests will go to …
> feat: add prometheus summary metrics

- tools/goctl/model/sql/model/postgresqlmodel.go
Create two same tables in different schemas would cause error.
Because the origin sql would find all the tables, then left join these tables to the  specific schema.
It didn't filter the specific schema when it use left join!
Like this:
```sql=
select t.num,t.field,t.type,t.not_null,t.comment, c.column_default, identity_increment
from (
SELECT a.attnum AS num,
c.relname,
a.attname     AS field,
t.typname     AS type,
a.atttypmod   AS lengthvar,
a.attnotnull  AS not_null,
b.description AS comment
FROM pg_class c,
pg_attribute a
LEFT OUTER JOIN pg_description b ON a.attrelid = b.objoid AND a.attnum = b.objsubid,
pg_type t
WHERE c.relname = $1
and a.attnum > 0
and a.attrelid = c.oid
and a.atttypid = t.oid
GROUP BY a.attnum, c.relname, a.attname, t.typname, a.atttypmod, a.attnotnull, …
```
> fix: goctl pg gen will extract all fields when the same table name exists in different schemas (#3496)

- internal/encoding/encoding.go
This pull request introduces several improvements to the encoding package:
1. **Refactoring for Code Reusability**: Introduced `encodeToJSON` to handle the encoding of TOML and YAML data to JSON, reducing duplicated code between `TomlToJson` and `YamlToJson`.
2. **Clearer Commenting**: Added English comments to each function for better clarity on its purpose and functionality.
3. **Enhanced Key Processing**: Updated functions related to key processing (`convertKeyToString` and `toStringKeyMap`) to ensure more consistent handling and conversion, particularly for ensuring map keys are of string type.
> feat: Optimize Encoding Functions and Add Descriptive Comments

- core/iox/read.go
- core/iox/read_test.go
- core/iox/tee.go
- core/iox/tee_test.go
- rest/handler/loghandler.go
It seems unnecessary to dump full Http Body to `logBrief`. 
This PR move limitBodyBytes to top layer using. This ensures that the size of the http body passed to logBrief has been limited.
> update: limit logBrief http body size

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
- core/mapping/yamlunmarshaler_test.go
> fix: unmarshal from number to string with incorrect error message

- core/proc/signals.go
> feat: add the SIGINT signal in signals.go to subscribe the user input ctrl+c to exit the application operation

- core/logx/richlogger.go
> fix: optimize logx for less GC objects

- tools/goctl/api/parser/g4/ast/apiparser.go
fixed: multiple files import the same api file
Program error prompt:
import cycle not allowed
But I didn't actually loop in the import file
reappear example:
execute: `goctl api go -api base.api -dir ./api  --style=go_zero`
base.api
```
syntax = "v1"
import "admin_work.api"
import "admin_report.api"
import "admin_retain.api"
```
public.api
```
syntax = "v1"
type UserInfo struct {}
type WorkInfo struct {}
```
query.api
```
syntax = "v1"
type QueryPage struct {}
```
admin_report.api
```
syntax = "v1"
import "query.api"
import "public.api"
@server(
prefix: report
)
service admin_svr {
@handler ReportList
post /list (ReportReq) returns (ReportResp)
}
type (
ReportReq {
QueryPage
}
ReportResp {
WorkInfo
UserInfo
}
)
```
admin_retain.api
```
syntax = "v1"
import "query.api"
@server(
prefix: …
```
> fix: multiple files import the same api file

- tools/goctl/rpc/generator/genpb.go
- tools/goctl/rpc/generator/genpb_test.go
> fix import error if generate multiple proto

- core/collection/ring.go
I added these lines to prevent the ring index from overflowing.
```go
// Add adds v into r.
func (r *Ring) Add(v any) {
r.lock.Lock()
defer r.lock.Unlock()
r.elements[r.index%len(r.elements)] = v
r.index++
// prevent ring index overflow
if r.index/len(r.elements) >= 2 {
r.index = r.index - len(r.elements)
}
}
```
The issue is from #2627.
> fix: prevent ring index overflow

- tools/goctl/model/sql/parser/parser.go
Issue #3766.
```bash
goctl model mysql ddl --src user_base.sql --dir .
```
```sql
CREATE TABLE `t_user_base` (
`f_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`f_uname` VARCHAR(16),
`f_phone` VARCHAR(20),
`f_email` VARCHAR(32),
`f_stop_time` DATETIME NOT NULL,
`f_create_time` DATETIME NOT NULL,
PRIMARY KEY (`f_id`),
UNIQUE KEY (`f_phone_number`) // error field
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
```
There is a case where the unique key `'f_phone_number'` does not match the `'f_phone'` field, which can cause a crash without displaying an error message.
And I found that there is a local variable that is not being used, but it will be processed in `Parse()`.
Do I need to mark it as a comment?
> fix: prevent a crash if there is a unique key constraint with a nil field.

- core/stores/redis/redis.go
Existing TTL functions cannot return -1 and -2.
> fix(redis): redis ttl -1 and -2

- core/service/servicegroup.go
Currently when stopping a service in a `ServiceGroup` the standard logger is used, this changes the log line to use the `logx` package and ensure all log lines are of the same format.
> fix(servicegroup): use logx for shutdown message

- core/stores/redis/redis.go
- core/stores/redis/redis_test.go
The current `Exists` function in go-zero's Redis only supports a single key, whereas go-redis's `Exists` can query multiple keys. 
However, directly altering go-zero's Redis implementation would lead to incompatibility between different versions of the method and would affect the implementation of the `Store` interface in `core/stores/kv/store.go`.
To ensure compatibility between versions, a new method named `ExistsMany` should be added as a transitional solution. A unified upgrade can be planned for a later major version release.
close #3765
```
// go-zero
// core/stores/redis.go:458
v, err := conn.Exists(ctx, key).Result()
// go-redis
Exists(ctx context.Context, keys ...string) *IntCmd
```
> feat:add redis ExistsMany method

- core/discov/internal/registry.go
etcd compact key reversion, this code will use old reversion, endless loop
this log is our production environment log, it's not always happen
> fix endless loop caused by ErrCompacted

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
When unmarshalling, if a negative float32 number is out of range,  the error  "out of range" would be returned.
> fix:  negative float32 overflow when unmarshalling

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
[issue3838](https://github.com/zeromicro/go-zero/issues/3838)
> fix(mapping): call fillSliceValue  panic if the value is nil

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
- rest/httpx/requests_test.go
> fix: issue 3840

- core/stores/sqlx/stmt.go
- core/stores/sqlx/stmt_test.go
Circuit breaker error is not reported in sqlx statement methods.
> feat: add break metrics for sqlx.statement

- core/stat/internal/cpu_linux.go
- core/stat/internal/cpu_other.go
In restricted environments, for example some PaaS, there is limited/no access to Linux cgroups. This can cause the following panic:
```
[2024-02-29 21:10:43] {"@timestamp":"2024-02-29T21:10:43.134Z","content":"cannot statfs cgroup root: no such file or directory
goroutine 4 [running]:
runtime/debug.Stack()
/layers/heroku_go/shim/go1.21.6/go/src/runtime/debug/stack.go:24 +0x5e
github.com/zeromicro/go-zero/core/logx.writeStack({0xc00012c4c0, 0x34})
/layers/heroku_go/shim/go-path/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/core/logx/logs.go:521 +0x34
github.com/zeromicro/go-zero/core/logx.ErrorStack({0xc000080b80?, 0xc000080c60?, 0xc000080c28?})
/layers/heroku_go/shim/go-path/pkg/mod/github.com/zeromicro/go-zero@v1.6.2/core/logx/logs.go:126 +0x2a …
```
> feat: add nocgroup build tag for systems without cgroup

- core/errorx/batcherror.go
- core/errorx/batcherror_test.go
BatchError.Add()  non thread safe,  `append` operation need  locked.
help to review it. thank!
@kevwan @kesonan
> fix: BatchError.Add() non thread safe

- core/stores/redis/redis.go
- core/stores/redis/redis_test.go
added `Zaddnx`, `ZaddnxCtx`, `ZaddnxFloat` and `ZaddnxFloatCtx` to impl `ZADDNX` command.
help to review it, plz ~~~
@kevwan
> feat(redis): added and impl `ZADDNX` command

- core/stores/redis/redis.go
- core/stores/redis/redis_test.go
The current go-zero Redis library lacks an implementation for the Redis MSET method, and it would be beneficial to add this. Implementing the Redis MSET method will facilitate batch insertion into Redis in the future, reducing network IO.
> feat:add redis mset func

- .dockerignore
- .github/dependabot.yml
- .github/workflows/go.yml
- readme-cn.md
- readme.md
- tools/goctl/.dockerignore
- tools/goctl/Dockerfile
- tools/goctl/test/integration/model/mongo/Dockerfile
- tools/goctl/test/integration/model/mongo/mongo.sh
* Run binaries as unprivileged user to improve security
* Copy whole timezone database to allow setting TZ env variable
* `docker run kevinwan/goctl --help` instead of `docker run kevinwan/goctl goctl --help`
* Remove files from Docker build context not needed for the resulting image
* Let Dependabot update Docker images and GitHub Actions
> feat: Improve Docker build

- rest/engine.go
The `notFoundHandler()` function builds its own chain, that will always contain the log middleware, even when `Middlewares.Log = false`.
This change ensures the log handler is only added to this chain conditionally.
> fix: only add log middleware to not found handler when enabled

- core/iox/textlinescanner.go
- core/stores/redis/hook.go
- tools/goctl/rpc/generator/genpb.go
- tools/goctl/util/format/format.go
- zrpc/internal/clientinterceptors/tracinginterceptor.go
Replace all error comparisons (matching format: err == xx) with errors.Is(err, xx).
> optimize: change err == xx to errors.Is(err, xx)

- core/discov/internal/registry.go
This PR closes [issue](https://github.com/zeromicro/go-zero/issues/3937)
> Add: Optimize the error log to be more specific

- tools/goctl/internal/flags/default_en.json
The demo url of posrgres from goctl tools usage is not correct. like this
The data source of database,like "root:password@tcp(127.0.0.1:3306)/database
seems copy from mysql side.
> fix the usage datasource url of postgresql (#4029)

- core/stores/builder/builder.go
`/core/stores/builder/builder.go`  There may be a spelling mistake.
> opton to option

- rest/httpx/responses.go
- rest/httpx/responses_test.go
1. support `httpx.Stream` method
2. set `timeout` to 0 to use `httpx.Stream` if multiple writes cannot complete within `timeout`
> feat: support http stream response

- tools/goctl/cmd/root.go
- tools/goctl/config/cmd.go
- tools/goctl/config/config.go
- tools/goctl/config/default.yaml
- tools/goctl/internal/flags/default_en.json
- tools/goctl/model/sql/converter/types.go
- tools/goctl/model/sql/converter/types_test.go
- tools/goctl/model/sql/example/sql/user.sql
- tools/goctl/model/sql/gen/imports.go
- tools/goctl/model/sql/parser/parser.go
- tools/goctl/model/sql/template/tpl/import-no-cache.tpl
- tools/goctl/model/sql/template/tpl/import.tpl
1. Support model data type reading from configuration files when GOCTL_EXPERIMENTAL is turned on.
2. Support custom data type mapping when GOCTL_EXPERIMENTAL is turned on
3. More info pls refer to 
https://go-zero.dev/docs/tutorials/cli/config(中文)
https://go-zero.dev/en/docs/tutorials/cli/config(English)
https://go-zero.dev/docs/tutorials/cli/model#%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84%E8%87%AA%E5%AE%9A%E4%B9%89(中文)
https://go-zero.dev/en/docs/tutorials/cli/model#type-mapping-customization(English)
> (goctl)feature/model config

- tools/goctl/pkg/golang/install.go
My GOPROXY env is https://goproxy.io,direct. 
When I use command `goctl env check --install --verbose --force`, always use goproxy.cn. 
goproxy.cn sometimes fails to download.
So I suggest to remove the GOPROXY env
> fix(goctl): GOPROXY env should set by ourself

- tools/goctl/Makefile
make build error:
make: command: Command not found
go build -ldflags="-s -w" goctl.go
> fix: make: command: Command not found

- core/mapping/unmarshaler.go
- rest/httpx/requests_test.go
feat: httpx.Parse supports parsing structures that implement the Unmarshaler interface
> feat: httpx.Parse supports parsing structures that implement the Unmarshaler interface

- core/trace/agent.go
- core/trace/config.go
Adds support for sending traces via otlphttp securely
> feat: add secure option for sending traces via otlphttp

- core/logx/logger.go
更新代码中的注释，我看到这里的注释还真以为是 debug 输出的 info level 的日志，后来检查 https://github.com/zeromicro/go-zero/pull/2411 发现代码是正确的，只是注释不正确，猜测是复制粘贴的时候未修改完全
> chore: fix the confused log level in comment

- tools/goctl/pkg/parser/api/parser/analyzer.go
- tools/goctl/pkg/parser/api/parser/testdata/invalid.api
1. disable nested struct for array and map type, the follow types all are invalid:
```go
type Demo {
Foo {} `json:"foo"` // invalid types: unsupported empty nestedt struct
Bar []{} `json:"foo"` // invalid types: slice elements unsupported nested struct
Bar [2]{} `json:"foo"` // invalid types: array elements unsupported nested struct
Bar map[{}]string `json:"foo"` // invalid types: map key elements unsupported nested struct
Bar map[int]{} `json:"foo"` // invalid types: map value elements unsupported nested struct
}
```
> disable nested struct for array and map type

- core/filex/file.go
- core/filex/file_test.go
#4217
Handle with empty file read and the condition that first is the same as last line and with out line break.
> fix: handle with read the empty file

- tools/goctl/api/dartgen/gendata.go
- tools/goctl/api/gogen/util.go
- tools/goctl/api/spec/name.go
- tools/goctl/api/spec/spec.go
- tools/goctl/api/tsgen/util.go
- tools/goctl/pkg/parser/api/parser/analyzer.go
1. Fixed the issue of the api structure being forced to be embedded after being generated
> (goctl): fix nested struct generation

- .github/workflows/go.yml
use newer syntax to specify go version.
> ci: update workflows to use go.mod instead of specifying go version

- core/errorx/batcherror.go
- core/errorx/batcherror_test.go
Replace the manual error string concatenation in errorArray.Error() with errors.Join() from the errors package to streamline error formatting.
refer to: https://github.com/zeromicro/go-zero/pull/3639
> refactor(core/errorx): use errors.Join simplify error handle

- tools/goctl/quickstart/quickstart.go
fix error while executing `goctl quickstart`
error:
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
> (goctl): fix quickstart error while reading go module info

- zrpc/resolver/internal/kubebuilder.go
- zrpc/resolver/internal/register.go
- zrpc/resolver/internal/register_k8s.go
- zrpc/resolver/internal/resolver.go
> feat: support build tag to reduce binary size w/o k8s

- core/logx/config.go
- core/logx/logs.go
- core/logx/rotatelogger.go
Added a custom log file name date format; when creating a file using the system's default file name date format, the file creation failed on the Windows platform because the file name contained the restriction character ":".
>  Add custom log file name date format

- zrpc/resolver/internal/discovbuilder.go
- zrpc/resolver/internal/kubebuilder.go
1. because resolver logic changed in grpc new versions
2. after idle, grpc close the builder and call Build method again
> fix: etcd scheme on grpc resolver

- tools/goctl/rpc/generator/genpb.go
To solve the problem of the disk full of code, I used soft links to move the directory where the code is saved, but the import path of the code generated by goctl is wrong
The problem occurs in tools/goctl/rpc/generator/mkdir.go SetPbDir()
d.ctx.Dir calculates the absolute path
pbDir does not calculate the absolute path
strings.TrimPrefix tries to remove d.ctx.Dir from pbDir but does not get a match
> fix the source code directory after the soft link

- tools/goctl/util/ctx/gomod.go
- tools/goctl/util/ctx/gomod_test.go
在go work下如果mod名字前缀一样会导致获取的不正确,末尾添加目录分隔符来确保一致
> fix: go work duplicate prefix get err

- rest/handler/loghandler.go
The `slowThreshold` is not used in the `logDetails` function to judge slow logs, so `SetSlowThreshold` not effective in function `logDetails`
> bugfix:`SetSlowThreshold` not effective in function `logDetails`

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
- rest/httpx/requests_test.go
- rest/httpx/util.go
- rest/httpx/util_test.go
- rest/router/patrouter_test.go
Supports three array parameter notations:
1. Standard notation: /api?names=alice&names=bob
2. Comma notation: /api?names=alice,bob
3. Bracket notation: /api?names[]=alice&names[]=bob
> feat: support form array in three notations

- core/proc/shutdown.go
- core/proc/shutdown_test.go
- core/service/servicegroup.go
- gateway/server.go
- gateway/server_test.go
> fix: service group not working well when callback takes long time

- core/proc/shutdown.go
- core/proc/shutdown_test.go
- core/service/serviceconf.go
Add `ProcConf` to `ServiceConf`, then we can use config file instead of `SetTimeToForceQuit` to set force quit time.
> feat: add ProcConf to make SetTimeToForceQuit configurable

- core/proc/shutdown+polyfill.go
- tools/goctl/internal/version/version.go
fix #4536 
But we need to finish it in 2 PRs. This one will fix service problem, the next one will use the latest release and fix the goctl windows problem.
> fix: goctl compile error on windows

- core/conf/config.go
Writing the wrong mapping field clearly helps troubleshoot the problem
> opt:Error message for optimizing mapping data method

- tools/goctl/pkg/parser/api/ast/infostatement.go
- tools/goctl/pkg/parser/api/ast/kvexpression.go
- tools/goctl/pkg/parser/api/ast/servicestatement.go
- tools/goctl/pkg/parser/api/parser/parser.go
- tools/goctl/pkg/parser/api/parser/parser_test.go
- tools/goctl/pkg/parser/api/parser/testdata/example.api
- tools/goctl/pkg/parser/api/scanner/scanner.go
- tools/goctl/pkg/parser/api/scanner/scanner_test.go
- tools/goctl/pkg/parser/api/token/token.go
> fix syntax of the  key expression

- core/discov/internal/registry.go
- core/discov/internal/registry_test.go
- core/discov/subscriber.go
- zrpc/resolver/internal/discovbuilder.go
- zrpc/resolver/internal/resolver.go
- zrpc/resolver/internal/resolver_test.go
Fix memory leak issue
There are two situations:
1. The same grpc client is created repeatedly.
2.  Resolver.Close is called when grpc enters idle mode, and the resolver will be re-created the next time rpc is called.
> fix memory leak of grpc resolver

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
I faced a minor problem when I used it.
for examlpe:
```api
type request {
Bytes []byte `json:"bytes"`
Name  string `json:"name"`
}
type response {}
service template {
@handler postDataTest
post /test (request) returns (response)
@handler getJsonData
get /get returns (request)
}
```
and `get` returns
```go
&types.Request{
Bytes: []byte("11122344wsss"),
Name:  "test",
}
```
It's ok when I visit `/get` api ,but when I put `/get` response (the json data of `request`) into `/test` error happend:
```log
fullName: `bytes`, error: `string: `MTExMjIzNDR3c3Nz`, error: `invalid character 'M' looking for beginning of value``
```
and I notice that ,there use json.Marshal() to make the response but use slef custom mapping.UnmarshalJsonReader to Unmarshal json data
so I just fix it (core in …
> fix:  wrong way of Unmarshal

- core/stores/redis/conf.go
- core/stores/redis/redis.go
Since Redis version 6.0, Redis has introduced access control based on username and password. Therefore, a new User configuration item has been added to the cache module.
> A new User property has been added to the RedisConf object.

- rest/httpx/requests.go
- rest/httpx/requests_test.go
> fix: different concreate types still cause panic

- tools/goctl/util/zipx/zipx.go
Potential fix for [https://github.com/zeromicro/go-zero/security/code-scanning/57](https://github.com/zeromicro/go-zero/security/code-scanning/57)
To fix the problem, we need to ensure that the file paths extracted from the zip archive do not contain any directory traversal elements (e.g., `..`). This can be done by validating the file paths before using them in file system operations.
1. Modify the `fileCopy` function to check for directory traversal elements in the file paths.
2. Ensure that the destination path is within the intended directory.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 57: Arbitrary file access during archive extraction ("Zip Slip")

- core/fs/files.go
- core/proc/goroutines.go
- core/proc/goroutines_test.go
- core/proc/profile.go
- core/proc/shutdown.go
- core/proc/shutdown_test.go
- core/proc/signals.go
- core/proc/signals_test.go
- tools/goctl/migrate/cancel.go
- tools/goctl/util/pathx/readlink.go
fix #2195 
Most widely used OS for production environments are Linux, Windows and FreeBSD.
> feat: support freebsd

- core/logx/logs.go
- core/logx/richlogger.go
- core/logx/writer.go
> fix: global fields apply to Third-party log module

- tools/goctl/util/ctx/gomod.go
- tools/goctl/util/ctx/gowork.go
- tools/goctl/util/ctx/gowork_test.go
- tools/goctl/util/ctx/modcheck.go
this PR fixed the error `no matched module` when using `goctl api` inside of a go workspace.
in go workspace, command `go list -m -f '{{.GoMod}}'` only lists modules declared in go.work, so goctl can't can the go.mod path even it's already initilized if the project is not in go.work.
to fix this, goctl should 
- use `go env GOMOD` to determine whether the project is a go module.
- check if the project is inside of a go workspace, if it does, it will use `go work use .` to add the project to go.work.
> feat(goctl): support go work (#4332)

- tools/goctl/pkg/parser/api/parser/analyzer_test.go
- tools/goctl/pkg/parser/api/parser/api.go
- tools/goctl/pkg/parser/api/parser/testdata/duplicate_path_expression.api
- tools/goctl/pkg/parser/api/parser/testdata/duplicate_path_expression_different_prefix.api
- tools/goctl/pkg/parser/api/parser/testdata/duplicate_path_expression_different_prefix__prefix_1.api
- tools/goctl/pkg/parser/api/parser/testdata/duplicate_path_expression_different_prefix__prefix_2.api
after upgrade to goctl@v1.7.6,
`goctl api go` with throw `duplicate_path_expression` err when there are two same path under **different** prefix.
fix the ast keyword when building path unique id.
> fix(goctl): allow `duplicate_path_expression` under different prefix

- core/mapping/fieldoptions.go
- core/mapping/unmarshaler.go
- core/mapping/utils.go
- rest/httpx/requests_test.go
> feat add tag switch to disable form array of split comma format

- core/mapping/marshaler.go
- core/mapping/marshaler_test.go
**"Add support for serialization of anonymous fields in httpc's Do method"**
---
During development, I discovered that the `Do` method in the `httpc` library does not currently support parsing anonymous struct fields. This leads to redundant code when defining request parameters for services that share common headers or fields. For example:
We define a generic request header structure `BaseHeader`:
```go
type BaseHeader struct {
OperationID string `header:"operationID"`
Token       string `header:"token"`
}
```
Then we embed this structure into a specific request struct:
```go
type GetTokenReq struct {
BaseHeader
UserID string `json:"userID"`
Secret string `json:"secret"`
}
```
In this scenario, the fields defined in `BaseHeader` (e.g., `OperationID` and `Token`) are not automatically …
> feat: Add support for serialization of anonymous fields in HTTP client(httpc)

- tools/goctl/api/spec/fn.go
Fix the issue in the previous API file where TypeScript code generated for fields of type form with optional did not mark the fields as optional.
> fix: form fields of request optional

- core/stores/sqlx/orm_test.go
More tests for orm_test, including unexported struct field with no pointer, unexported struct field with no pointer and no tags, and different error cases for `TestAnonymousStructPrError`
Refer to #4745
> chore: add more orm_test

- tools/goctl/api/swagger/swagger.go
fix: the parameter `required` in the Swagger document generated for repair is incorrect
> fix: the parameter "required" in the Swagger document generated for repair is incorrect

- core/mapping/marshaler.go
- core/mapping/marshaler_test.go
if it is not optional in struct, it panics when do reflect on reflect.isNil, because array never be nullable.
> fix(marshaler): fix bug when marshal array

- tools/goctl/api/tsgen/util.go
#4717
Fix: Resolve the issue where the goctl api ts command fails to generate correct TypeScript code when field names contain hyphens.
Before:
After:
> fix: goctl api tsgen

- tools/goctl/pkg/parser/api/parser/parser.go
- tools/goctl/pkg/parser/api/parser/parser_test.go
This PR fixes issue #4825 by modifying the API parser to support special characters like periods (`.`) in API route paths.
The go-zero API parser was previously rejecting file extensions in route paths, such as `/api_jsonrpc.php`. 
This was causing a syntax error: `expected 'IDENT', got '.'` when users tried to define an API route with a filename extension.
I've updated the `parsePathItem` function in the parser to accept and properly handle periods in route paths, which allows routes like `/api_jsonrpc.php` to be correctly parsed.
- Modified `parsePathItem` in `/tools/goctl/pkg/parser/api/parser/parser.go` to handle period tokens in path segments
- Added comprehensive test cases to verify the fix works with various file extensions (`.php`, `.html`, `.json`, etc.)
Added a new test …
> fix: allow special characters like periods in API route paths

- tools/goctl/api/cmd.go
- tools/goctl/api/swagger/example/example_cn.api
- tools/goctl/api/swagger/path.go
- tools/goctl/api/swagger/response.go
- tools/goctl/api/swagger/swagger.go
1. update goctl version to `1.8.3`
2. supported custom biz code definition in method level.
> release goctl swagger

- tools/goctl/api/swagger/const.go
- tools/goctl/api/swagger/path.go
- tools/goctl/build.env
- tools/goctl/change.md
- tools/goctl/internal/version/version.go
- [features] Supported operation id for swagger
- Updated version to 1.8.4-beta
[goctl-1.8.4-beta-windows-arm64.zip](https://github.com/user-attachments/files/20273526/goctl-1.8.4-beta-windows-arm64.zip)
[goctl-1.8.4-beta-windows-amd64.zip](https://github.com/user-attachments/files/20273530/goctl-1.8.4-beta-windows-amd64.zip)
[goctl-1.8.4-beta-darwin-arm64.zip](https://github.com/user-attachments/files/20273540/goctl-1.8.4-beta-darwin-arm64.zip)
[goctl-1.8.4-beta-darwin-amd64.zip](https://github.com/user-attachments/files/20273534/goctl-1.8.4-beta-darwin-amd64.zip)
[goctl-1.8.4-beta-linux-amd64.zip](https://github.com/user-attachments/files/20273537/goctl-1.8.4-beta-linux-amd64.zip)
[goctl-1.8.4-beta-darwin-amd64.zip](https://github.com/user-attachments/files/20273541/goctl-1.8.4-beta-darw …
> goctl: 1.8.4-beta

- core/hash/consistenthash_test.go
As I comprehend it, this UT `TestConsistentHashTransferOnFailure` aims to validate the transfer ratio of `ConsistentHash` when a physical node is taken offline, but the transferred count is always zero when given `index := 41`, because of the key size only has 20.
```go
const (
keySize     = 20
requestSize = 1000
)
func TestConsistentHashTransferOnFailure(t *testing.T) {
// index 41 is not exists in ConsistentHash
index := 41
keys, newKeys := getKeysBeforeAndAfterFailure(t, "localhost:", index)
// transferred is always 0
var transferred int
for k, v := range newKeys {
if v != keys[k] {
transferred++
}
}
ratio := float32(transferred) / float32(requestSize)
assert.True(t, ratio < 2.5/float32(keySize), fmt.Sprintf("%d: %f", index, ratio))
}
func getKeysBeforeAndAfterFailure(t *testing.T, …
```
> test(hash): modify TestConsistentHashTransferOnFailure to more reasonable test transfer ratio

- tools/goctl/api/swagger/const.go
- tools/goctl/api/swagger/example/example_cn.api
- tools/goctl/api/swagger/parameter.go
- tools/goctl/api/swagger/path.go
- tools/goctl/api/swagger/properties.go
1. swagger
- Add operationId
- fix path parameter error when `useDefinitions`
**Assets**
----
[goctl-1.8.4-beta-windows-arm64.zip](https://github.com/user-attachments/files/20412588/goctl-1.8.4-beta-windows-arm64.zip)
[goctl-1.8.4-beta-windows-amd64.zip](https://github.com/user-attachments/files/20412589/goctl-1.8.4-beta-windows-amd64.zip)
[goctl-1.8.4-beta-darwin-arm64.zip](https://github.com/user-attachments/files/20412590/goctl-1.8.4-beta-darwin-arm64.zip)
[goctl-1.8.4-beta-darwin-amd64.zip](https://github.com/user-attachments/files/20412593/goctl-1.8.4-beta-darwin-amd64.zip)
[goctl-1.8.4-beta-linux-arm64.zip](https://github.com/user-attachments/files/20412596/goctl-1.8.4-beta-linux-arm64.zip)
[goctl-1.8.4-beta-linux-amd64.zip](https://github.com/user-attachments/files/20412598/goctl-1. …
> goctl: v1.8.4-beta

- rest/handler/timeouthandler.go
Fix a spelling error in the `timeoutWriter.Header()` method comment where "underline" should be "underlying".
- **File**: `rest/handler/timeouthandler.go`
- **Line**: 153
- **Change**: `underline` → `underlying`
```go
// Before
// Header returns the underline temporary http.Header.
// After
// Header returns the underlying temporary http.Header.
```
- **Risk Level**: None (comment-only change)
- **Backward Compatibility**: ✅ Fully compatible
- **Performance Impact**: None
- **API Changes**: None
No functional testing required as this is a comment-only change. The spelling correction improves the accuracy of the method documentation.
The word "underlying" is the correct term in this context, as it refers to the base or foundational `http.Header` that the method returns. "Underline" would …
> fix: correct spelling of 'underlying' in Header method comment

- core/mapping/unmarshaler.go
- core/mapping/unmarshaler_test.go
```
type inner struct {
Duration time.Duration `json:"duration"`
}
func TestUnmarshalerPanic(t *testing.T) {
content := `
{
"duration": 1
}
`
var in inner
err := conf.LoadFromJsonBytes([]byte(content), &in) // panic here
fmt.Println(in, err)
}
```
Panic before repair：
> // === RUN   TestUnmarshalerPanic
> //--- FAIL: TestUnmarshalerPanic (0.00s)
> //panic: interface conversion: interface {} is json.Number, not string [recovered]
> //	panic: interface conversion: interface {} is json.Number, not string
error after repair：
> === RUN   TestUnmarshalerPanic
> {0s} unexpected type json.Number, expected a string value for field duration
> --- PASS: TestUnmarshalerPanic (0.00s)
> fix: the time.Duration type panics due to numerical values

- tools/goctl/config/default.yaml
- tools/goctl/model/sql/model/postgresqlmodel.go
- **Go**: 1.24
- **go-zero**: 1.8.4
- **goctl**: 1.8.4
- **PostgreSQL**: 15.13 on x86_64-pc-linux-musl
This PR fixes an issue where PostgreSQL `numeric` and `decimal` types are incorrectly mapped to `double` in the PostgreSQL to MySQL type mapping, preventing users from properly customizing type mappings for high-precision numeric fields.
When using `goctl model` command to generate ORM code, `numeric` type fields are mapped to `float64`. While this works in most cases, it causes issues when users try to customize type mappings according to the [[official documentation](https://go-zero.dev/en/docs/tutorials/cli/model#type-mapping-customization)](https://go-zero.dev/en/docs/tutorials/cli/model#type-mapping-customization).
1. Create a PostgreSQL table with `numeric` type:
```sql
CREATE …
```
> fix: Fix PostgreSQL numeric type mapping in goctl model generation

- tools/goctl/api/swagger/parameter.go
- tools/goctl/api/swagger/parameter_test.go
- Before correction:
- After correction
- Verify the correct identification of the POST method and JSON tags
- Key test: Non-POST methods should not return true (bug fixed before)
- Test the key parameter generation scenarios
- Verify the correct generation of the body parameter
- Test the handling of nil and non-struct types
> Fix POST JSON parameter determination logic (goctl api swagger) & Add some unit test.

- core/collection/set.go
- core/collection/set_test.go
- Compile-time type safety: No runtime type checking required
- Better performance: Reduced overhead from type assertions and reflection
- Simplified API: Single Add method replaces multiple type-specific methods
- Backward compatibility: Existing Set implementation remains unchanged
benchmark:
`goos: darwin
goarch: arm64
pkg: github.com/zeromicro/go-zero/core/collection
cpu: Apple M2 Pro
BenchmarkTypedIntSet-10         13094462               127.6 ns/op            33 B/op          0 allocs/op
BenchmarkTypedStringSet-10      34456252                33.28 ns/op            6 B/op          1 allocs/op
BenchmarkTypedSetInt-10         16142239               149.8 ns/op            49 B/op          0 allocs/op
BenchmarkRawSet-10               8121650               262.7 ns/op            92 B/op …
> feat: add generic TypedSet with 2x performance boost and compile-time

- core/discov/publisher.go
- core/discov/publisher_test.go
1. Problem
There is an issue in production where when go-zero uses etcd, under certain conditions, the registered key disappears, causing frontend services to be unable to find backend services.
2. Reproduction conditions
Then I simulated it locally by deleting the registered key in etcd. It won't regenerate, even if the service process still exists. So I used a simple strategy for re-registration: if getting this key doesn't exist, then put it. After using the new strategy, deleting this key will regenerate it.
(Since the time spent handling this was relatively short, only 30 minutes, the PR may not be very complete. Welcome to discuss with the author)
> fix: Issue with etcd key disappearing and unable to auto-re-register

- tools/goctl/api/gogen/gen.go
- tools/goctl/api/gogen/genconfig.go
- tools/goctl/api/gogen/genhandlers.go
- tools/goctl/api/gogen/genhandlerstest.go
- tools/goctl/api/gogen/genlogic.go
- tools/goctl/api/gogen/genlogictest.go
- tools/goctl/api/gogen/genmain.go
- tools/goctl/api/gogen/genroutes.go
- tools/goctl/api/gogen/gensvc.go
- tools/goctl/pkg/golang/path.go
- tools/goctl/quickstart/mono.go
Support projectPkg template variables in config, handler, logic, main, and svc template files to facilitate highly customized templates for your own projects
> feat: Support projectPkg template variables in config, handler, logic, main, and svc template files

- gateway/internal/eventhandler.go
- gateway/internal/eventhandler_test.go
修复 #5110. 目前的响应实现，对于Header会加Grpc-Metadata-前缀。对于Trailer会加Grpc-Trailer-前缀
> fix:issue-5110

- tools/goctl/api/gogen/sse_handler.tpl
https://github.com/zeromicro/go-zero/issues/5182
https://github.com/zeromicro/go-zero/issues/5155
https://github.com/zeromicro/go-zero/issues/5094
1.  The `close(client)` call is placed in the top-level `http.HandlerFunc`'s `defer`, which means the channel is only closed when the entire HTTP request handler returns.
2.  The actual event generation (`l.{{.Call}}`) runs in a separate `threading.GoSafeCtx` goroutine. When this goroutine finishes sending all events, the `client` channel remains open because `close(client)` is not executed within its scope.
3.  The main `for` loop, which reads from the `client` channel, will then block indefinitely on `case data := <-client:` because it never receives a "closed" signal, even though no more events will be sent.
4.  Furthermore, the `case data …
> fix: SSE handler blocking

- rest/server_test.go
- tools/goctl/model/sql/command/migrationnotes/migrationnotes.go
- tools/goctl/pkg/protoc/protoc.go
This PR corrects several minor typos in comments and documentation across the codebase. The changes are non-functional and purely textual to improve clarity and maintain a clean, professional codebase.
- Corrected misspellings:
- `preivous` → `previous`
- `comamnd` → `command`
- `unsupport` → `unsupported`
These fixes help enhance readability and eliminate minor distractions during development and code reviews.
No logic or functionality has been modified. All changes are restricted to comments or non-executable doc annotations.
> chore: fix typos
