zeromicro/go-zero

tools/goctl/goctl.go

remote auto update

---

core/syncx/once_test.go
core/utils/version.go
core/utils/version_test.go

I want append  CustomVersionCompare

【rich function】

---

readme.md
tools/goctl/api/gogen/util.go

correct parent packet for gomod

correct parent packet for gomod

---

tools/goctl/api/gogen/util.go

fix windows slash

---

go.mod
go.sum
tools/goctl/api/ktgen/cmd.go
tools/goctl/api/ktgen/funcs.go
tools/goctl/api/ktgen/gen.go
tools/goctl/goctl.go

```shell
goctl api kt -api example.api -dir output -pkg com.example.me.output
```

Add goctl Kotlin support

---

tools/goctl/api/gogen/genlogic.go

fix format

---

tools/goctl/api/gogen/gen.go
tools/goctl/api/gogen/util.go
tools/goctl/configgen/genconfig.go
tools/goctl/util/path.go

fix config yaml gen

---

example/shorturl/api/internal/logic/expandlogic.go
example/shorturl/api/internal/logic/shortenlogic.go

这两个文件中需要添加`svcCtx `和字段填充，不然后续该`demo`会出现无法编译和`panic`的问题

fix shorturl example code

---

tools/goctl/util/project/project.go

fix GOMOD env fetch bug

---

tools/goctl/model/sql/gen/findonebyfield.go
tools/goctl/model/sql/gen/gen.go

rename file and function name

---

readme-en.md

chore: fix typos

---

core/syncx/sharedcalls_test.go

add sharedcalls test

---

doc/bookstore-en.md
doc/bookstore.md
doc/shorturl-en.md
doc/shorturl.md

在看着教程学习 go-zero 框架的时候，遇到两次忘记创建目录而跟教程最终的目录有点差别，觉得加上一些文字说明会更好一点，也降低学习者的心智负担😅

perfect the bookstore and shorturl doc

---

readme-en.md
readme.md

docs: format markdown and add go mod in demo

---

core/syncx/sharedcalls.go

Removes unused parameters for SharedCalls

---

tools/goctl/api/gogen/gen_test.go
tools/goctl/api/gogen/util.go
tools/goctl/api/parser/servicestate.go
tools/goctl/util/project/project.go

1. support no request and response:
@handler NoRequestNoResponseHandler
get /greet/from
2. replace windows slash
3. add more test

route support no request and response

---

tools/goctl/api/format/format.go
tools/goctl/api/gogen/gen.go
tools/goctl/api/gogen/gen_test.go
tools/goctl/api/gogen/gentypes.go
tools/goctl/api/new/newservice.go
tools/goctl/api/parser/parser.go
tools/goctl/api/parser/util.go
tools/goctl/goctl.go
tools/goctl/rpc/cli/cli.go

add more test

---

tools/goctl/api/gogen/gen_test.go
tools/goctl/api/parser/basestate.go
tools/goctl/api/parser/entity.go
tools/goctl/api/parser/rootstate.go
tools/goctl/api/parser/util.go

api support for comment double slash //

api support for comment double slash //

---

tools/goctl/api/gogen/gen.go
tools/goctl/api/gogen/gen_test.go
tools/goctl/api/gogen/genroutes.go
tools/goctl/api/gogen/gentypes.go
tools/goctl/api/new/newservice.go
tools/goctl/api/parser/basestate.go
tools/goctl/api/parser/entity.go
tools/goctl/goctl.go

1. group support multi level folder
2. remove force flag

1. group support multi level folder 2. remove force flag

---

tools/goctl/api/format/format.go
tools/goctl/api/format/format_test.go
tools/goctl/api/gogen/gen_test.go
tools/goctl/api/parser/apifileparser.go
tools/goctl/api/util/util.go

1. type should not define nested
2. more test

type should not define nested

---

readme.md

modify image url

---

tools/goctl/api/apigen/gen.go

set default handler value

---

core/collection/rollingwindow.go
tools/goctl/Makefile

- check go.mod before build docker image
- update version (#226)
- set default handler value (#228)
- Improve Makefile robustness (#224)
- modify the service name from proto (#230)
- optimization (#221)
- simplify code, format makefile

format makefile, simplify code

---

core/collection/rollingwindow.go
tools/goctl/Makefile

simplify code

---

core/collection/rollingwindow.go

only line 139 change to w.size by benying, others by kevwan.
thanks a lot !

some optimize by kevwan and benying

---

core/collection/rollingwindow.go
rest/httpx/requests.go
tools/goctl/Makefile
tools/goctl/api/gogen/genhandlers.go
tools/goctl/docker/docker.go
tools/goctl/docker/template.go

```dockerfile
ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
```

optimize docker file generation, make docker build faster

---

go.mod
go.sum
tools/goctl/api/spec/fn.go
tools/goctl/api/spec/tags.go

optimized parse tag

---

rest/server_test.go

add more tests

---

core/executors/periodicalexecutor.go
core/executors/periodicalexecutor_test.go

The old fix decrease the rate,  the problem still exists.

fix bug #317

---

tools/goctl/api/format/format.go
tools/goctl/api/format/format_test.go
tools/goctl/api/javagen/gencomponents.go
tools/goctl/api/spec/fn.go
tools/goctl/api/tsgen/genpacket.go
tools/goctl/api/tsgen/vars.go

optimized goctl format
1. auto alignment type def
2. auto remove struct keyword

optimized goctl format

---

tools/goctl/api/gogen/genmiddleware.go

fix return in for

---

tools/goctl/api/javagen/gencomponents.go
tools/goctl/api/javagen/util.go
tools/goctl/api/parser/util.go

Java optimized

---

tools/goctl/api/javagen/gencomponents.go
tools/goctl/api/javagen/genpacket.go
tools/goctl/api/javagen/util.go
tools/goctl/api/parser/parser.go
tools/goctl/api/spec/fn.go
tools/goctl/api/spec/spec.go
tools/goctl/api/tsgen/genpacket.go
tools/goctl/api/tsgen/util.go

 fix inner type generate error

---

tools/goctl/api/gogen/util.go
tools/goctl/api/javagen/gencomponents.go
tools/goctl/api/javagen/genpacket.go
tools/goctl/api/parser/parser.go
tools/goctl/api/spec/fn.go
tools/goctl/goctl.go

optimized go generator and format

optimized go generator and format

---

tools/goctl/plugin/plugin.go

fix type convert error

---

tools/goctl/api/dartgen/genapi.go
tools/goctl/api/dartgen/gendata.go
tools/goctl/api/dartgen/genvars.go
tools/goctl/api/dartgen/util.go
tools/goctl/api/dartgen/vars.go

optimize code

---

rest/config.go

Modify the http content-length max range : 30MB --> 32MB
Because we are programmer  :)
Thanks @kevwan

Modify the http content-length max range : 30MB --> 32MB

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

support hscan in redis

---

readme.md

Signed-off-by: Liang Zheng <microyahoo@163.com>

fix readme.md error

---

1.go
core/stores/redis/redis.go
core/stores/redis/redis_test.go

Add stores redis command Rpop
=== RUN   TestRedis_List
--- PASS: TestRedis_List (0.00s)
PASS
Process finished with exit code 0

Support redis command Rpop

---

core/collection/ring.go
core/collection/ring_test.go

ring struct add lock

---

tools/goctl/api/docgen/doc.go
tools/goctl/api/docgen/gen.go
tools/goctl/goctl.go

optimized markdown generate output

Code optimized

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

redis add bitcount

---

core/conf/config.go

I am navigating the code and find this simple typo. Mark this as my first contribution to this project, a neglectable one although, LOL.

fix a simple typo

---

core/logx/logs.go
core/stores/redis/conf.go
core/stores/redis/redis.go
core/stores/redis/redis_test.go
core/stores/redis/redisclientmanager.go
core/stores/redis/redisclustermanager.go

redis增加tls支持

---

go.mod
go.sum
tools/goctl/api/parser/g4/ast/apiparser.go
tools/goctl/api/parser/g4/ast/ast.go
tools/goctl/api/parser/g4/gen/api/apiparser_base_visitor.go
tools/goctl/api/parser/g4/gen/api/apiparser_lexer.go
tools/goctl/api/parser/g4/gen/api/apiparser_parser.go
tools/goctl/api/parser/g4/gen/api/apiparser_visitor.go
tools/goctl/api/parser/g4/gen/api/baseparser.go

* fix antlr `ambiguous import`

replace antlr module

---

tools/goctl/api/parser/g4/ast/apiparser.go

* fix issue: https://github.com/zeromicro/goctl-swagger/issues/6

fix issue: https://github.com/zeromicro/goctl-swagger/issues/6

---

tools/goctl/model/sql/example/sql/user.sql
tools/goctl/model/sql/model/informationschemamodel.go
tools/goctl/model/sql/parser/parser.go
tools/goctl/model/sql/parser/parser_test.go
tools/goctl/model/sql/util/newline.go

* replace column comment with nil space
* fix bug: generates model code error while the column contains new-line character in comment

Optimize model nl

---

tools/goctl/api/parser/g4/ast/type.go
tools/goctl/api/parser/parser.go
tools/goctl/api/parser/parser_test.go
tools/goctl/api/spec/name.go
tools/goctl/api/spec/spec.go

* Add document & comment for api.Spec

Add document & comment for spec

---

zrpc/internal/client.go

Fix a typo

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

redis集合Set，新增求交集操作，实现Sinter、Sinterstore两个方法，并修改了TestRedis_Set单元测试

Add Sinter,Sinterstore & Modify TestRedis_Set

---

rest/httpx/requests.go
rest/httpx/requests_test.go

[WIP]Add parse headers info

---

tools/goctl/rpc/generator/gen_test.go
tools/goctl/rpc/generator/gencall.go
tools/goctl/rpc/generator/genlogic.go
tools/goctl/rpc/generator/genserver.go
tools/goctl/rpc/generator/test.proto
tools/goctl/rpc/parser/stream.proto

* Add Supported to generate grpc stream
* Add grpc generates unit test

To generate grpc stream, fix issue #616

---

tools/goctl/rpc/generator/gencall.go
tools/goctl/rpc/generator/genlogic.go
tools/goctl/rpc/generator/genserver.go

生成正确的streamBody。之前的生成的是固定的。正确的是rpc.Name + Client 和rpc.Name + Server

Fix the error stream method name

---

tools/goctl/goctl.go
tools/goctl/model/sql/README.MD
tools/goctl/model/sql/command/command.go
tools/goctl/model/sql/command/command_test.go
tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/gen_test.go
tools/goctl/model/sql/gen/keys.go
tools/goctl/model/sql/gen/keys_test.go
tools/goctl/model/sql/parser/parser.go
tools/goctl/model/sql/parser/parser_test.go

Fixed [#830](https://github.com/tal-tech/go-zero/issues/830)

Added database prefix of cache key.

---

tools/goctl/api/gogen/gen.go
tools/goctl/docker/docker.go
tools/goctl/goctl.go
tools/goctl/kube/kube.go
tools/goctl/model/mongo/mongo.go
tools/goctl/model/sql/command/command.go
tools/goctl/rpc/cli/cli.go
tools/goctl/tpl/templates.go
tools/goctl/util/file.go

* Add flag `--home` to specify the goctl home to save the templates, for more information, please execute command `goclt help`
* Fix issue #831

fix issue #831

---

tools/goctl/goctl.go
tools/goctl/model/sql/command/command.go

add correct example for pg's url, reference #793

---

tools/goctl/goctl.go
tools/goctl/rpc/cli/cli.go

生成proto的方法没有home参数。本身是有proto template这个模板的，所以应该也有home参数。

add goctl rpc template home flag

---

core/mapping/unmarshaler.go
rest/httpx/requests.go
rest/httpx/requests_test.go

fix http header binding failure bug #885

---

core/contextx/unmarshaler_test.go
core/contextx/valueonlycontext_test.go
core/logx/logs.go
core/mapping/unmarshaler.go
tools/goctl/model/sql/builderx/builder.go
tools/goctl/util/file.go

fix: 解决golint 部分警告

---

tools/goctl/model/sql/gen/template.go

* fix missing `updateMethodTemplateFile`

fix missing `updateMethodTemplateFile`

---

tools/goctl/model/sql/command/command.go
tools/goctl/model/sql/command/command_test.go
tools/goctl/model/sql/example/makefile
tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/keys.go
tools/goctl/util/env/env_test.go
tools/goctl/util/string.go
tools/goctl/util/string_test.go

* Add unit test for [tools/goctl/util/env/env.go](https://github.com/tal-tech/go-zero/blob/master/tools/goctl/util/env/env.go)
* fix #907 
* optimize cache key generation in case without `database` value

Optimize model naming

---

tools/goctl/model/sql/command/command.go

format code

---

CONTRIBUTING.md
rest/httpx/responses.go
rest/httpx/responses_test.go

httpx.Error response without body

---

tools/goctl/api/apigen/gen.go
tools/goctl/api/apigen/template.go
tools/goctl/goctl.go
tools/goctl/tpl/templates.go

add api template file

---

core/errorx/atomicerror.go
core/errorx/atomicerror_test.go

fix AtomicError panic when Set nil (#1049)

---

tools/goctl/api/new/newservice.go
tools/goctl/api/new/template.go
tools/goctl/goctl.go
tools/goctl/tpl/templates.go

`goctl api new` command support `--home` flag
```
NAME:
goctl api new - fast create api service
USAGE:
goctl api new [command options] [arguments...]
OPTIONS:
--home value  the goctl home path of the template
```

update goctl api

---

core/syncx/resourcemanager.go
core/syncx/resourcemanager_test.go
core/syncx/spinlock_test.go

1. add more tests for resourcemanager and spinlock
2. set resources to nil on `Close()`

test: add more tests

---

rest/engine.go
rest/internal/starter.go
rest/server.go
rest/server_test.go

Signed-off-by: lihaowei <haoweili35@gmail.com>

[update] add plugin config

---

core/stores/sqlx/tx.go

distributed transaction manager dtm need to interact with go-zero's sqlx.Session

feat: add NewSessionFromTx to interact with other orm

---

tools/goctl/api/dartgen/gen.go
tools/goctl/api/docgen/gen.go
tools/goctl/api/gogen/genroutes.go
tools/goctl/api/javagen/gen.go
tools/goctl/api/ktgen/cmd.go
tools/goctl/api/spec/fn.go
tools/goctl/api/spec/spec.go
tools/goctl/api/tsgen/gen.go
tools/goctl/util/string.go

* Supported route generates with prefix

Generate route with prefix

---

tools/goctl/docker/docker.go
tools/goctl/docker/template.go
tools/goctl/goctl.go

goctl docker command add -version to specifying different versions

goctl docker command add -version

---

core/stores/redis/redis_test.go
core/stores/redis/redislock.go

redislock use stringx.randn replace randomStr func

chore: redislock use stringx.randn replace randomStr func

---

zrpc/client.go
zrpc/client_test.go
zrpc/config.go
zrpc/server.go

server side quota control not implemented yet, will be done in v1.2.4

feat: disable grpc retry, enable it in v1.2.4

---

core/hash/consistenthash_test.go

fix TestConsistentHashIncrementalTransfer Test Function duplicate temporary variable

Duplicate temporary variable

---

zrpc/client.go
zrpc/client_test.go
zrpc/config.go
zrpc/server.go

This reverts commit 09eb53f30819f14b434f6459077f74dadb35b4fc.

Revert "feat: enable retry for zrpc (#1237)"

---

zrpc/client.go
zrpc/client_test.go
zrpc/config.go
zrpc/server.go

This reverts commit 37b12a30d7bf83ad623b65844915ee6f6ea498a7.

Revert "Revert "feat: enable retry for zrpc (#1237)""

---

tools/goctl/api/gogen/genlogic.go
tools/goctl/api/parser/g4/ast/service.go
tools/goctl/api/parser/g4/test/service_test.go

```
service primitive-api {
@handler BoolHandler
get /bool returns (bool)
@handler BoolsHandler
get /bools returns ([]bool)
@handler IntHandler
get /int returns (int)
@handler IntsHandler
get /ints returns ([]int)
@handler StringHandler
get /string returns (string)
@handler StringsHandler
get /strings returns ([]string)
}
```
Checkout the example code at: https://github.com/kevwan/zero-issues/blob/main/987/primitive.api

fixes #987

---

tools/goctl/bug/bug.go
tools/goctl/bug/env.go
tools/goctl/bug/issue.go
tools/goctl/go.sum
tools/goctl/goctl.go

Support `goctl bug`: you can report a issue by `goctl bug`, then it will open a web browser and fill in an issue template

Feat goctl bug

---

rest/handler/loghandler.go

This reverts commit 2cdf5e73958149f889630cb57ec7e0879c061aed.

Revert "排除客户端中断导致的503错误 (#1343)"

---

rest/internal/security/contentsecurity.go

cancel the assignment and judge later

chose: cancel the assignment and judge later

---

tools/goctl/api/apigen/gen.go
tools/goctl/api/gogen/gen.go
tools/goctl/api/new/newservice.go
tools/goctl/docker/docker.go
tools/goctl/goctl.go
tools/goctl/kube/kube.go
tools/goctl/model/mongo/mongo.go
tools/goctl/model/sql/command/command.go
tools/goctl/rpc/cli/cli.go
tools/goctl/util/file.go
tools/goctl/util/file_test.go
tools/goctl/util/git.go

* Add `--remote`
* Support to generate code by Golang template from git repo

feat: Add --remote

---

tools/goctl/model/sql/command/command_pg_test.go
tools/goctl/model/sql/parser/parser.go

1. fix pg model struct haven't tag
2. add pg command test from datasource

Fix goctl pg model generation without tag

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

Ltrim is the implementation of redis ltrim command

feat: support the ltrim command of redis

---

tools/goctl/goctl.go
tools/goctl/migrate/migrate.go
tools/goctl/migrate/mod.go

* Add signal check
* Add deprecated pkg check

patch: goctl migrate

---

core/mapping/yamlunmarshaler.go

Signed-off-by: chenquan <chenquan.dev@foxmail.com>

fix: fix a typo

---

core/stores/cache/cache.go
core/stores/cache/cache_test.go
core/stores/cache/cachenode.go

Signed-off-by: chenquan <chenquan.dev@foxmail.com>

feat: support ctx in `Cache`

---

tools/goctl/goctl.go
tools/goctl/kube/deployment.go
tools/goctl/kube/job.go
tools/goctl/kube/kube.go

add the serviceAccount of deployment

add the serviceAccount of deployment

---

tools/goctl/env/check.go
tools/goctl/env/env.go
tools/goctl/goctl.go
tools/goctl/internal/errorx/errorx.go
tools/goctl/pkg/collection/sortedmap.go
tools/goctl/pkg/collection/sortedmap_test.go
tools/goctl/pkg/downloader/downloader.go
tools/goctl/pkg/env/env.go
tools/goctl/pkg/goctl/goctl.go
tools/goctl/pkg/golang/bin.go
tools/goctl/pkg/golang/install.go
tools/goctl/pkg/protoc/protoc.go
tools/goctl/pkg/protocgengo/protocgengo.go
tools/goctl/pkg/protocgengogrpc/protocgengogrpc.go
tools/goctl/util/env/env.go
tools/goctl/util/pathx/file.go
tools/goctl/util/stringx/string.go
tools/goctl/util/zipx/zipx.go

- goctl environment variable view
- goctl environment detection
- goctl dependency installation

Feature: Add goctl env

---

core/logx/logs.go
core/logx/tracelogger_test.go
tools/goctl/go.mod

build: update goctl dependency ddl-parser to v1.0.3

---

tools/goctl/api/dartgen/gendata.go
tools/goctl/api/dartgen/util.go
tools/goctl/api/dartgen/util_test.go
tools/goctl/api/dartgen/vars.go

fix: goctl api dart support `form` tag

---

tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/imports.go
tools/goctl/model/sql/gen/insert.go
tools/goctl/model/sql/template/import.go
tools/goctl/model/sql/template/insert.go

refer to https://github.com/lib/pq/issues/24

fix:goctl pg gen of insert code

---

tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/imports.go
tools/goctl/model/sql/gen/insert.go
tools/goctl/model/sql/template/import.go
tools/goctl/model/sql/template/insert.go

Reverts zeromicro/go-zero#1591

Revert "fix:goctl pg gen of insert code"

---

tools/goctl/api/dartgen/gendata.go
tools/goctl/api/dartgen/util.go
tools/goctl/api/dartgen/util_test.go

`user-defined-struct` array in api file, such as `[]Bars` below
``` golang
type Foo {
Bars  []Bar   `json:"bars"`
}
```
dart_gen should return `List<Bar>`

fix(goctl): dart gen user defined struct array

---

tools/goctl/api/ktgen/gen.go

Signed-off-by: Ziyi Zhang <soasurs@gmail.com>

fix(goctl): kotlin code generation error

---

core/collection/timingwheel.go

comments from https://www.reddit.com/r/golang/comments/txecj7/a_timing_wheel_implementation_optimized_for/

chore: add doc for TimingWheel

---

tools/goctl/rpc/cli/cli.go

show help when running goctl rpc template without any flags

---

tools/goctl/api/parser/g4/ast/apiparser.go
tools/goctl/api/parser/g4/ast/apiparser_test.go
tools/goctl/api/parser/g4/ast/importstack.go

feat(goctl): supports api  multi-level importing

---

tools/goctl/goctl.go
tools/goctl/rpc/cli/cli.go

before: 
after: <img width="1416" alt="Screen Shot 2022-03-21 at 14 52 06" src="https://user-images.githubusercontent.com/1277047/159216195-553b1575-0bad-4b3c-964e-a34e22b1192a.png">

improve goctl rpc new

---

tools/goctl/rpc/cli/zrpc.go

show help when running goctl rpc protoc without any flags

---

tools/goctl/docker/docker.go

show help when running goctl docker without any flags

---

tools/goctl/api/apigen/gen.go

show help when running goctl api without any flags

---

tools/goctl/rpc/execx/execx.go
tools/goctl/util/ctx/context.go
tools/goctl/util/ctx/gomod.go
tools/goctl/util/ctx/gomod_test.go
tools/goctl/util/ctx/modcheck.go

feat(goctl): go work multi-module support

---

core/stores/mon/collection.go
core/stores/redis/hook.go
core/stores/redis/hook_test.go

Signed-off-by: chenquan <chenquan.dev@gmail.com>

chore: optimize code

---

go.mod
go.sum
zrpc/internal/client.go

- remove the deprecated grpc.WithBalancerName

feat: upgrade grpc to 1.46

---

core/stat/remotewriter.go
rest/httpc/vars.go
rest/httpx/vars.go
tools/goctl/api/dartgen/vars.go
tools/goctl/api/ktgen/apibase.tpl

feat: add charset utf-8 in json content type

---

core/logx/logs.go
core/logx/logs_test.go
core/logx/tracelogger_test.go

fix time, duration, slice types on logx.Field

---

tools/goctl/rpc/generator/template_test.go

fix:tools/goctl/rpc/generator/template_test.go file has wrong parameters

---

core/stores/mon/collection.go
core/stores/mon/collection_test.go
core/stores/mon/model.go
core/stores/mon/trace.go
core/stores/mon/util.go
core/stores/mon/util_test.go
core/stores/redis/hook.go
core/stores/redis/hook_test.go
core/stores/sqlx/sqlconn.go
core/stores/sqlx/trace.go
core/stores/sqlx/tx.go

Signed-off-by: chenquan <chenquan.dev@gmail.com>

refactor: refactor trace in redis & sql & mongo

---

core/logx/logs_test.go
core/logx/syslog_test.go
zrpc/client.go
zrpc/internal/client.go
zrpc/internal/client_test.go
zrpc/internal/rpcserver.go

feat: support WithStreamClientInterceptor for zrpc clients

---

tools/goctl/docker/cmd.go
tools/goctl/docker/docker.go
tools/goctl/docker/docker.tpl
tools/goctl/model/sql/template/model.go

chore: refine docker for better compatible with package main

---

rest/engine.go
rest/server.go
rest/server_test.go

feat: print routes

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go

fix: The validation of tag "options" is not working with int/uint type

---

tools/goctl/kube/cmd.go
tools/goctl/kube/deployment.tpl
tools/goctl/kube/kube.go

In practice, it is necessary to set the image pull policy through parameter, thanks

feat: add 'imagePullPolicy' parameter for 'goctl kube deploy'

---

go.sum
rest/httpc/requests.go
rest/httpc/requests_test.go

feat: add trace in httpc

---

tools/goctl/api/gogen/genhandlers.go

Remove legacy code 
Reference: 9fe868ad

Remove legacy code

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go
core/mapping/utils.go
core/mapping/utils_test.go
rest/internal/encoding/parser_test.go

fix: type matching supports string to int

fix: type matching supports string to int

---

core/jsonx/json.go
core/jsonx/json_test.go

Create a new method MarshalToString to jsonx

feat: add method to jsonx

---

core/utils/version.go

refactor:remove duplicate codes

---

gateway/config.go
gateway/server.go

hello.proto 文件可能依赖 common.proto
需要支持多个proto set 文件

support mulitple protoset files

---

tools/goctl/api/gogen/config.tpl
tools/goctl/api/gogen/genconfig.go

fix: #2216

---

zrpc/config.go
zrpc/internal/rpcserver.go
zrpc/internal/server.go
zrpc/server.go

feat: rpc add health check function configuration optional

---

rest/server.go
rest/server_test.go

fix: place cors middleware in the front of other middlewares.

---

core/stores/kv/store.go
core/stores/kv/store_test.go
core/stores/redis/redis.go
core/stores/redis/redis_test.go

feat(redis): add ZaddFloat & ZaddFloatCtx

---

tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/gen_test.go

https://github.com/zeromicro/go-zero/issues/2301
here in func defaultGenerator.createFile we regen package name which is different with NewDefaultGenerator

fix #2301,package conflict generated by ddl

---

core/collection/safemap.go
core/collection/safemap_test.go

safemap add Range method

---

tools/goctl/kube/cmd.go
tools/goctl/kube/deployment.tpl
tools/goctl/kube/kube.go
tools/goctl/tproxy.yaml

feat: support targetPort option in goctl kube

---

tools/goctl/api/cmd.go

fix goctl help message

---

tools/goctl/model/sql/gen/gen_test.go

fix(goctl): fix the unit test bug of goctl

---

core/logc/logs.go
core/logc/logs_test.go
core/logx/fields.go
core/logx/fields_test.go
core/logx/logs_test.go
core/logx/writer.go
core/logx/writer_test.go

feat: add logc package, support AddGlobalFields for both logc and logx.

---

zrpc/internal/clientinterceptors/durationinterceptor.go

help with code review, please~ @kevwan

fix: replace Infof() with Errorf() in DurationInterceptor (#2495)

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go

feat: support uuid.UUID in mapping

---

rest/handler/tracinghandler.go
rest/handler/tracinghandler_test.go

feat(trace): support for disabling tracing of specified `spanName`

---

zrpc/resolver/internal/kube/targetparser.go
zrpc/resolver/internal/kube/targetparser_test.go
zrpc/resolver/internal/kubebuilder.go

Target: k8s://namespace/service-rpc-svc:8001
To
Target: k8s://namespace/service-rpc-svc

The default port is used when there is no port number for k8s

---

tools/goctl/go.mod
tools/goctl/go.sum

bump goctl deps cobra version to v1.6.1

Fixes #2603 bump goctl cobra version to macos completion help bug

---

core/logx/config.go
core/logx/logs.go

logx conf add DisableStat
---------------------------
Log:
Mode: console
Path: logs/api
Level: info
DisableStat: false

logx conf add DisableStat

---

tools/goctl/model/mongo/readme.md
tools/goctl/model/mongo/template/model.tpl

This PR includes two parts:
- Change the implementation of the `Update` function from calling `m.conn.ReplaceOne` to `m.conn.UpdateOne`.
- Add return values for `Update` and `Delete` functions
First of all, I have a small team that has been using go-zero for some time. You can click [here](https://github.com/xh-polaris) to view our organization.
As for the first change, I want to say that in the original case, if I want to update a document, I must first call the Find function to get it, and then call the Update function to completely update it. **This is not atomic**, which will cause conflicts in the case of concurrency.
If you change `ReplaceOne` to `UpdateOne` and add `omitempty` to all fields' bson tag in the type definition file, **you can update the desired fields as needed** …

fix(mongo): modify the generated update function and add return values for update and delete functions

---

rest/httpx/requests.go

Just define an interface without introduce any other dependencies in this library. Users can easily integrate it with https://github.com/go-playground/validator, etc.
Inspired by https://zhuanlan.zhihu.com/p/566267318

feat: add configurable validator for httpx.Parse

---

core/conf/config.go
core/conf/config_test.go

fix: config map cannot handle case-insensitive keys.

---

tools/goctl/api/cmd.go
tools/goctl/rpc/cmd.go
tools/goctl/rpc/generator/generator.go

- use config.DefaultFormat
- var log conflict

optimized goctl code

---

tools/goctl/api/cmd.go
tools/goctl/api/dartgen/gen.go
tools/goctl/api/dartgen/genvars.go
tools/goctl/api/dartgen/vars.go

1. add scheme config for user to specify serverHost scheme(http、https)，default is http
2. dd http header Content-Type.Without this header, the backend server cannot parse JSON data correctly.

Update goclt dart gen: Add scheme config and content-type header

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

1. add LpopCount,RpopCount
2. add test cases

feat(redis):add LpopCount,RpopCount

---

tools/goctl/model/sql/template/tpl/model-new.tpl
tools/goctl/model/sql/template/tpl/model.tpl

Export cache.Option param to NewXXXModel()

---

zrpc/internal/config.go
zrpc/internal/rpcserver.go
zrpc/internal/serverinterceptors/statinterceptor.go
zrpc/internal/serverinterceptors/statinterceptor_test.go
zrpc/server.go

refactor(zrpc): prefer static config for zrpc server statinterceptor

---

tools/goctl/rpc/generator/gencall.go

#3103 
This code is not good, but I have no other ideas

fix:multipule flag client go package name

---

tools/goctl/api/apigen/gen.go
tools/goctl/api/gogen/gen.go
tools/goctl/api/javagen/gen.go
tools/goctl/api/tsgen/gen.go
tools/goctl/api/validate/validate.go
tools/goctl/cmd/root.go
tools/goctl/cmd/usage.go
tools/goctl/compare/testdata/testdata.go
tools/goctl/docker/docker.go
tools/goctl/go.mod
tools/goctl/go.sum
tools/goctl/kube/kube.go
tools/goctl/migrate/migrate.go
tools/goctl/tpl/templates.go
tools/goctl/util/console/console.go
tools/goctl/util/pathx/file.go

feat: replaced color package to support Windows

---

rest/handler/timeouthandler.go
rest/handler/timeouthandler_test.go

fix: timeout handler not implementing http.Flusher

---

core/stores/redis/hook.go
core/stores/sqlx/stmt.go
rest/handler/prometheushandler.go
tools/goctl/api/gogen/genroutes.go
zrpc/internal/clientinterceptors/prometheusinterceptor.go
zrpc/internal/serverinterceptors/prometheusinterceptor.go

Use the methods provided by go sdk to simplify the code

update:Use the Milliseconds method of duration to get the number of milliseconds

---

core/trace/agent.go
core/trace/agent_test.go
core/trace/config.go

Support optional otel global initialization for #3284

feat: support optional otel global initialization for #3284

---

tools/goctl/.gitignore
tools/goctl/internal/flags/default_en.json
tools/goctl/rpc/cli/cli.go
tools/goctl/rpc/cli/zrpc.go
tools/goctl/rpc/cmd.go
tools/goctl/rpc/generator/gen.go
tools/goctl/rpc/generator/mkdir.go

whether to generate rpc client option , default=true
eg : 
goctl rpc protoc --client=false ........
goctl rpc new --client =false ...

add  whether to generate rpc client option

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go

feature:
optimize the error output when slice/map lacks elements, and give precise error information

feat: optimize mapping error

---

core/stores/sqlc/cachedsql.go
core/stores/sqlc/cachedsql_test.go

make cachedsql can use QueryRowsPartial,QueryRowPartial

add:func() QueryRowsPartial,QueryRowPartial into cachedsql.go

---

core/stores/sqlc/cachedsql.go
core/stores/sqlc/cachedsql_test.go

Reverts zeromicro/go-zero#3512

Revert "add:func() QueryRowsPartial,QueryRowPartial into cachedsql.go"

---

tools/goctl/api/parser/parser.go
tools/goctl/pkg/parser/api/parser/analyzer.go
tools/goctl/pkg/parser/api/parser/api.go
tools/goctl/pkg/parser/api/parser/testdata/invalid.api

1. syntax code block detection support optional
2. Support json tag optional
3. Route sorting

optimize: fix experimental api 

---

core/stores/builder/builder.go

refactor: update builder.go

---

readme.md

Updated the misleading information and made some text improvements to improve documentation [🔗](https://github.com/zeromicro/go-zero#backgrounds-of-go-zero)
Fixes #3631

Update documenation section #background

---

go.mod
go.sum

详情请看
https://github.com/grpc/grpc-go/releases/tag/v1.58.3

Upgrade grpc-go，fix 0day problem.

---

core/logx/readme.md

docs fix typo in core/logx/readme.md

---

rest/internal/starter.go
zrpc/internal/rpcserver.go
zrpc/internal/rpcserver_test.go

update restful/grpc servers shutdown from wrap up to to shutdown stage.

chore: update restful/grpc servers shutdown stages

---

code-of-conduct.md

I have enhanced/improved the CODE_OF_CONDUCT Guidelines via updating the CODE_OF_CONDUCT.md file. Making it more clear/comprehensible for the users, ensuring that users can easily access and understand the CODE_OF_CONDUCT instructions information.
I have also corrected the minor grammatical errors etc. that were present in the file previously.
@kevwan 
Kindly review my PR and merge it please.

Enhanced the CODE_OF_CONDUCT Guidelines

---

tools/goctl/api/dartgen/genapi.go
tools/goctl/api/dartgen/gendata.go
tools/goctl/api/dartgen/vars.go

add map type

---

tools/goctl/model/sql/gen/gen_test.go
tools/goctl/pkg/parser/api/parser/api.go
tools/goctl/pkg/parser/api/parser/filter.go
tools/goctl/pkg/parser/api/parser/parser.go
tools/goctl/pkg/parser/api/parser/parser_test.go
tools/goctl/pkg/parser/api/parser/testdata/example.api
tools/goctl/pkg/parser/api/parser/testdata/service_test.api
tools/goctl/pkg/parser/api/scanner/scanner.go

1. fix #3833 
2. fix parser error in case root path `/`

fix(goctl)/new parser

---

rest/httpx/requests_test.go

chore: add more tests

---

core/trace/agent.go

fix: StopAgent panics when trace agent disabled

---

rest/httpx/requests_test.go
rest/httpx/util.go

I would like to fix the array parsing issue
could you please to help check
https://github.com/zeromicro/go-zero/issues/4025

fix(httpx): support array field for request dto

---

tools/goctl/readme-cn.md
tools/goctl/readme.md

chore(goctl): update readme

---

core/bloom/bloom.go
core/bloom/setscript.lua
core/bloom/testscript.lua
core/limit/periodlimit.go
core/limit/periodscript.lua
core/limit/tokenlimit.go
core/limit/tokenscript.lua
core/stores/redis/delscript.lua
core/stores/redis/lockscript.lua
core/stores/redis/redislock.go

Reasons to move：
Better coding experience, syntax prompts highlighted, avoid some wrong.

feat: migrate lua script to lua file

---

tools/goctl/model/sql/gen/customized.go
tools/goctl/model/sql/gen/gen.go
tools/goctl/model/sql/gen/template.go
tools/goctl/model/sql/template/template.go

add customized.tpl for model template

---

core/bloom/bloom.go
core/breaker/breaker.go
rest/httpc/requests.go
rest/server.go
zrpc/internal/balancer/p2c/p2c.go
zrpc/resolver/internal/discovbuilder.go
zrpc/resolver/internal/kubebuilder.go

initialize some slice type variables

chore: initialize some slice type variables

---

zrpc/resolver/internal/discovbuilder.go
zrpc/resolver/internal/kubebuilder.go

Reverts zeromicro/go-zero#4121

Revert "fix: etcd scheme on grpc resolver"

---

rest/handler/loghandler.go

fix: DetailedLog format.

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go

Reverts zeromicro/go-zero#4405

Revert "feat/conf_map_required"

---

tools/goctl/internal/version/version.go

👋 seeing some release version report issue in https://github.com/Homebrew/homebrew-core/pull/207426. Bump version to fix the report.

fix: update version to match with the release

---

rest/server.go
rest/server_test.go

fix: make test purpose method private

---

zrpc/internal/serverinterceptors/statinterceptor.go
zrpc/internal/serverinterceptors/statinterceptor_test.go

fix: SlowThreshold configuration not taking effect

---

core/stores/redis/redis.go
core/stores/redis/redis_test.go

https://redis.io/docs/latest/commands/getdel/

feat: support redis getdel command

---

mcp/config.go
mcp/config_test.go
mcp/integration_test.go
mcp/readme.md
mcp/server.go
mcp/server_test.go
mcp/types.go
mcp/types_test.go
mcp/util.go
mcp/util_test.go
mcp/vars.go
mcp/vars_test.go

This package implements a Model Context Protocol (MCP) server in Go that facilitates real-time communication between AI models and clients using Server-Sent Events (SSE). The implementation provides a framework for building AI-assisted applications with bidirectional communication capabilities.
- **Real-time Communication**: Robust SSE-based communication system that maintains persistent connections with clients
- **Connection Management**: Client registration, message broadcasting, and client cleanup mechanisms
- **Event Handling**: Event types for tools, prompts, and resources changes
- **Request Processing**: Complete JSON-RPC request processor for handling MCP protocol methods
- **Response Formatting**: Proper response formatting according to JSON-RPC specifications
- **Error …

feat: mcp server sdk

---

gateway/server_test.go

add http to http gatway test case -- method not allpwed

feat: add http to http method test case

---

tools/goctl/internal/flags/default_en.json
tools/goctl/model/cmd.go
tools/goctl/model/sql/command/command.go

add cache prefix support to pg

feat:add cache prefix support to pg

---

mcp/config.go
mcp/config_test.go
mcp/integration_test.go
mcp/parser.go
mcp/parser_test.go
mcp/readme.md
mcp/server.go
mcp/server_test.go
mcp/types.go
mcp/types_test.go
mcp/util.go
mcp/util_test.go
mcp/vars.go
mcp/vars_test.go

1. **Code Organization & Architecture**:
- Added a dedicated `parser.go` with `ParseArguments` function that properly handles both `map[string]string` and `map[string]any` input types
- Moved helper functions to `util.go` for better code structure
- Improved type handling with consistent content type constants
2. **Type System Enhancements**:
- Added proper typed content wrappers (typedTextContent, typedImageContent, typedAudioContent)
- Changed `roleType` to `RoleType` for better public API consistency
- Exported important constants like `ContentTypeText`, `ContentTypeImage`, etc.
- Default to `ContentTypeObject` for schema when not explicitly set
3. **Documentation**:
- Significantly expanded the readme.md with comprehensive API documentation
- Added detailed examples for tools, …

feat: improve mcp

---

tools/goctl/api/swagger/swagger.go

fix https://github.com/zeromicro/go-zero/issues/4898

fix(goctl): Fix getting swagger consume types

---

tools/goctl/api/spec/tags.go
tools/goctl/api/spec/tags_test.go

(goctl): fix #4943

---

rest/engine.go
rest/engine_test.go
rest/server.go
rest/server_test.go
rest/types.go

see #4785, will be merged in v1.8.5

fix: timeout 0s not working

---

core/mapping/unmarshaler.go
core/mapping/unmarshaler_test.go

chore: optimize pr 4979

---

core/stores/sqlx/config.go
core/stores/sqlx/config_test.go
core/stores/sqlx/rwstrategy.go
core/stores/sqlx/rwstrategy_test.go
core/stores/sqlx/sqlconn.go
core/stores/sqlx/sqlconn_test.go
core/stores/sqlx/tx.go
core/stores/sqlx/tx_test.go

sqlx read-write separation feature support

sql read write support

---

rest/engine.go
rest/internal/response/withcoderesponsewriter.go

realted issue :https://github.com/zeromicro/go-zero/issues/4451
according to https://stackoverflow.com/questions/27097084/http-server-read-write-timeouts-and-server-side-events

Fix SSE timeout will affected by  http.Server 's WriteTimeout

---

rest/handler/loghandler.go
rest/handler/loghandler_test.go

fix: large memory usage on detail logging post requests

---

gateway/server.go
gateway/server_test.go

Add custom middleware support to the gateway module:
Changes:
- Add `WithMiddleware` function that accepts one or more middleware functions
- Support both single and multiple middleware registration
- Maintain compatibility with existing `WithHeaderProcessor` functionality
- Add comprehensive tests for middleware functionality
Usage Examples
Single Middleware
```go
server := gateway.MustNewServer(config, gateway.WithMiddleware(authMiddleware))
```
Multiple Middlewares (Single Call)
```go
server := gateway.MustNewServer(config, 
gateway.WithMiddleware(authMiddleware, loggingMiddleware, rateLimitMiddleware))
```
Multiple Middlewares (Multiple Calls)
```go
server := gateway.MustNewServer(config, 
gateway.WithMiddleware(authMiddleware),
gateway.WithMiddleware(loggingMiddleware), …
```

feat(gateway): add custom middleware support with onion model

---

tools/goctl/model/sql/model/postgresqlmodel.go

```
var p2m = map[string]string{
"int8":        "bigint",
"float8":      "double",
"float4":      "float",
"int2":        "smallint",
"int4":        "integer",
"timestamptz": "timestamp",
"uuid":        "varchar", // Added to support UUID fields
}
```
make goctl model support uuid type

fear(model);add uuid:varchar to p2m
